
CREATE TABLE D_PAIS_CONTINENTE(
 COD_ISO_2 varchar(2)
 ,DES_PAIS varchar(30)
 ,COD_ISO_3 varchar(3)
 ,COD_CONTINENTE varchar(2)
 ,DES_CONTINENTE varchar(30)
);


insert into D_PAIS_CONTINENTE VALUES('DZ','Algeria','DZA','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('AO','Angola','AGO','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('SH','Ascension','SHN','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('BJ','Benin','BEN','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('BW','Botswana','BWA','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('BF','Burkina Faso','BFA','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('BI','Burundi','BDI','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('CM','Cameroon','CMR','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('CV','Cape Verde Islands','CPV','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('CF','Central African Republic','CAF','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('TD','Chad Republic','TCD','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('KM','Comoros','COM','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('CG','Congo','COG','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('CD','Dem. Republic of the Congo','COD','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('DJ','Djibouti','DJI','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('EG','Egypt','EGY','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('GQ','Equatorial Guinea','GNQ','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('ER','Eritrea','ERI','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('ET','Ethiopia','ETH','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('GA','Gabon Republic','GAB','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('GM','Gambia','GMB','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('GH','Ghana','GHA','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('GN','Guinea','GIN','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('GW','Guinea-Bissau','GNB','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('CI','Ivory Coast','CIV','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('KE','Kenya','KEN','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('LS','Lesotho','LSO','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('LR','Liberia','LBR','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('LY','Libya','LBY','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('MG','Madagascar','MDG','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('MW','Malawi','MWI','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('ML','Mali Republic','MLI','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('MR','Mauritania','MRT','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('MU','Mauritius','MUS','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('YT','Mayotte Island','MYT','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('MA','Morocco','MAR','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('MZ','Mozambique','MOZ','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('NA','Namibia','NAM','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('NE','Niger Republic','NER','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('NG','Nigeria','NGA','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('ST','Principe','STP','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('RE','Reunion Island','REU','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('RW','Rwanda','RWA','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('ST','Sao Tome','STP','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('SN','Senegal Republic','SEN','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('SC','Seychelles','SYC','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('SL','Sierra Leone','SLE','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('SO','Somalia Republic','SOM','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('ZA','South Africa','ZAF','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('SS','South Sudan','SSD','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('SH','St. Helena','SHN','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('SD','Sudan','SDN','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('SZ','Swaziland','SWZ','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('TZ','Tanzania','TZA','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('TG','Togo','TGO','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('TN','Tunisia','TUN','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('UG','Uganda','UGA','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('CD','Zaire','COD','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('ZM','Zambia','ZMB','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('TZ','Zanzibar','TZA','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('ZW','Zimbabwe','ZWE','AF','ÁFRICA')
insert into D_PAIS_CONTINENTE VALUES('AF','Afghanistan','AFG','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('AM','Armenia','ARM','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('AZ','Azerbaijan','AZE','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('BH','Bahrain','BHR','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('BD','Bangladesh','BGD','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('BT','Bhutan','BTN','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('BN','Brunei','BRN','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('KH','Cambodia','KHM','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('CN','China','CHN','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('CX','Christmas Island','CXR','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('CC','Cocos Islands','CCK','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('IO','Diego Garcia','IOT','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('GE','Georgia','GEO','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('HK','Hong Kong','HKG','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('IN','India','IND','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('ID','Indonesia','IDN','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('IR','Iran','IRN','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('IQ','Iraq','IRQ','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('IL','Israel','ISR','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('JP','Japan','JPN','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('JO','Jordan','JOR','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('KZ','Kazakhstan','KAZ','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('KW','Kuwait','KWT','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('KG','Kyrgyzstan','KGZ','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('LA','Laos','LAO','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('LB','Lebanon','LBN','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('MO','Macau','MAC','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('MY','Malaysia','MYS','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('MV','Maldives','MDV','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('MN','Mongolia','MNG','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('MM','Myanmar','MMR','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('NP','Nepal','NPL','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('KP','North Korea','PRK','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('OM','Oman','OMN','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('PK','Pakistan','PAK','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('PS','Palestine','PSE','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('PH','Philippines','PHL','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('QA','Qatar','QAT','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('SA','Saudi Arabia','SAU','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('SG','Singapore','SGP','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('KR','South Korea','KOR','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('LK','Sri Lanka','LKA','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('SY','Syria','SYR','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('TW','Taiwan','TWN','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('TJ','Tajikistan','TJK','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('TH','Thailand','THA','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('TR','Turkey','TUR','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('TM','Turkmenistan','TKM','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('AE','United Arab Emirates','ARE','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('UZ','Uzbekistan','UZB','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('VN','Vietnam','VNM','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('YE','Yemen','YEM','AS','ASIA')
insert into D_PAIS_CONTINENTE VALUES('AS','American Samoa','ASM','OC','OCEANÍA')
insert into D_PAIS_CONTINENTE VALUES('AU','Australia','AUS','OC','OCEANÍA')
insert into D_PAIS_CONTINENTE VALUES('NZ','Chatham Island, NZ','NZL','OC','OCEANÍA')
insert into D_PAIS_CONTINENTE VALUES('CK','Cook Islands','COK','OC','OCEANÍA')
insert into D_PAIS_CONTINENTE VALUES('TL','East Timor','TLS','OC','OCEANÍA')
insert into D_PAIS_CONTINENTE VALUES('FM','Federated States of Micronesia','FSM','OC','OCEANÍA')
insert into D_PAIS_CONTINENTE VALUES('FJ','Fiji Islands','FJI','OC','OCEANÍA')
insert into D_PAIS_CONTINENTE VALUES('PF','French Polynesia','PYF','OC','OCEANÍA')
insert into D_PAIS_CONTINENTE VALUES('GU','Guam','GUM','OC','OCEANÍA')
insert into D_PAIS_CONTINENTE VALUES('KI','Kiribati','KIR','OC','OCEANÍA')
insert into D_PAIS_CONTINENTE VALUES('MP','Mariana Islands','MNP','OC','OCEANÍA')
insert into D_PAIS_CONTINENTE VALUES('MH','Marshall Islands','MHL','OC','OCEANÍA')
insert into D_PAIS_CONTINENTE VALUES('UM','Midway Islands','UMI','OC','OCEANÍA')
insert into D_PAIS_CONTINENTE VALUES('NR','Nauru','NRU','OC','OCEANÍA')
insert into D_PAIS_CONTINENTE VALUES('NC','New Caledonia','NCL','OC','OCEANÍA')
insert into D_PAIS_CONTINENTE VALUES('NZ','New Zealand','NZL','OC','OCEANÍA')
insert into D_PAIS_CONTINENTE VALUES('NU','Niue','NIU','OC','OCEANÍA')
insert into D_PAIS_CONTINENTE VALUES('NF','Norfolk Island','NFK','OC','OCEANÍA')
insert into D_PAIS_CONTINENTE VALUES('PW','Palau','PLW','OC','OCEANÍA')
insert into D_PAIS_CONTINENTE VALUES('PG','Papua New Guinea','PNG','OC','OCEANÍA')
insert into D_PAIS_CONTINENTE VALUES('MP','Saipan','MNP','OC','OCEANÍA')
insert into D_PAIS_CONTINENTE VALUES('WS','Samoa','WSM','OC','OCEANÍA')
insert into D_PAIS_CONTINENTE VALUES('SB','Solomon Islands','SLB','OC','OCEANÍA')
insert into D_PAIS_CONTINENTE VALUES('TK','Tokelau','TKL','OC','OCEANÍA')
insert into D_PAIS_CONTINENTE VALUES('TO','Tonga','TON','OC','OCEANÍA')
insert into D_PAIS_CONTINENTE VALUES('TV','Tuvalu','TUV','OC','OCEANÍA')
insert into D_PAIS_CONTINENTE VALUES('VU','Vanuatu','VUT','OC','OCEANÍA')
insert into D_PAIS_CONTINENTE VALUES('UM','Wake Island','UMI','OC','OCEANÍA')
insert into D_PAIS_CONTINENTE VALUES('WF','Wallis and Futuna Islands','WLF','OC','OCEANÍA')
insert into D_PAIS_CONTINENTE VALUES('AL','Albania','ALB','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('AD','Andorra','AND','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('AT','Austria','AUT','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('BY','Belarus','BLR','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('BE','Belgium','BEL','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('BA','Bosnia and Herzegovina','BIH','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('BG','Bulgaria','BGR','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('HR','Croatia','HRV','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('CY','Cyprus','CYP','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('CZ','Czech Republic','CZE','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('DK','Denmark','DNK','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('EE','Estonia','EST','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('FO','Faroe Islands','FRO','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('FI','Finland','FIN','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('FR','France','FRA','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('DE','Germany','DEU','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('GI','Gibraltar','GIB','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('GR','Greece','GRC','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('HU','Hungary','HUN','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('IS','Iceland','ISL','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('IE','Ireland','IRL','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('IM','Isle of Man','IMN','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('IT','Italy','ITA','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('RS','Kosovo','XKX','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('LV','Latvia','LVA','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('LI','Liechtenstein','LIE','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('LT','Lithuania','LTU','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('LU','Luxembourg','LUX','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('MK','Macedonia','MKD','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('MT','Malta','MLT','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('MD','Moldova','MDA','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('MC','Monaco','MCO','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('ME','Montenegro','MNE','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('NL','Netherlands','NLD','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('NO','Norway','NOR','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('PL','Poland','POL','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('PT','Portugal','PRT','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('RO','Romania','ROU','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('RU','Russia','RUS','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('SM','San Marino','SMR','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('RS','Serbia','SRB','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('SK','Slovakia','SVK','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('SI','Slovenia','SVN','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('ES','Spain','ESP','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('SE','Sweden','SWE','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('CH','Switzerland','CHE','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('UA','Ukraine','UKR','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('GB','United Kingdom','GBR','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('VA','Vatican city','VAT','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('RS','Yugoslavia','RSB','EU','EUROPA')
insert into D_PAIS_CONTINENTE VALUES('AI','Anguilla','AIA','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('AG','Antigua and Barbuda','ATG','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('AW','Aruba','ABW','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('BS','Bahamas','BHS','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('BB','Barbados','BRB','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('BZ','Belize','BLZ','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('BM','Bermuda','BMU','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('BQ','Bonaire','BES','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('VG','British Virgin Islands','VGB','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('CA','Canada','CAN','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('KY','Cayman Islands','CYM','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('CR','Costa Rica','CRI','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('CU','Cuba','CUB','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('CW','Curacao','CUW','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('DM','Dominica','DMA','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('DO','Dominican Republic','DOM','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('SV','El Salvador','SLV','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('GL','Greenland','GRL','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('GD','Grenada and Carriacuou','GRD','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('GP','Guadeloupe','GLP','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('GT','Guatemala','GTM','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('HT','Haiti','HTI','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('HN','Honduras','HND','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('JM','Jamaica','JAM','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('MQ','Martinique','MTQ','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('MX','Mexico','MEX','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('PM','Miquelon','SPM','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('MS','Montserrat','MSR','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('CW','Netherlands Antilles','ANT','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('KN','Nevis','KNA','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('NI','Nicaragua','NIC','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('PA','Panama','PAN','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('PR','Puerto Rico','PRI','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('BQ','Saba','BES','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('BQ','Sint Eustatius','BES','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('SX','Sint Maarten','SXM','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('KN','St. Kitts','KNA','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('LC','St. Lucia','LCA','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('PM','St. Pierre and Miquelon','SPM','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('VC','St. Vincent','VCT','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('TT','Trinidad and Tobago','TTO','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('TC','Turks and Caicos Islands','TCA','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('US','United States','USA','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('VI','US Virgin Islands','VIR','NA','AMÉRICA NORTE')
insert into D_PAIS_CONTINENTE VALUES('AR','Argentina','ARG','SA','AMÉRICA SUR')
insert into D_PAIS_CONTINENTE VALUES('BO','Bolivia','BOL','SA','AMÉRICA SUR')
insert into D_PAIS_CONTINENTE VALUES('BR','Brazil','BRA','SA','AMÉRICA SUR')
insert into D_PAIS_CONTINENTE VALUES('CL','Chile','CHL','SA','AMÉRICA SUR')
insert into D_PAIS_CONTINENTE VALUES('CO','Colombia','COL','SA','AMÉRICA SUR')
insert into D_PAIS_CONTINENTE VALUES('EC','Ecuador','ECU','SA','AMÉRICA SUR')
insert into D_PAIS_CONTINENTE VALUES('FK','Falkland Islands','FLK','SA','AMÉRICA SUR')
insert into D_PAIS_CONTINENTE VALUES('GF','French Guiana','GUF','SA','AMÉRICA SUR')
insert into D_PAIS_CONTINENTE VALUES('GY','Guiana','GUF','SA','AMÉRICA SUR')
insert into D_PAIS_CONTINENTE VALUES('GY','Guyana','GUY','SA','AMÉRICA SUR')
insert into D_PAIS_CONTINENTE VALUES('PY','Paraguay','PRY','SA','AMÉRICA SUR')
insert into D_PAIS_CONTINENTE VALUES('PE','Peru','PER','SA','AMÉRICA SUR')
insert into D_PAIS_CONTINENTE VALUES('SR','Suriname','SUR','SA','AMÉRICA SUR')
insert into D_PAIS_CONTINENTE VALUES('UY','Uruguay','URY','SA','AMÉRICA SUR')
insert into D_PAIS_CONTINENTE VALUES('VE','Venezuela','VEN','SA','AMÉRICA SUR')

