-- sp_refreshview [VF_PBI_ACEITE_CONFORME]
-- select * from [VF_PBI_ACEITE_CONFORME]

ALTER VIEW [dbo].[VF_PBI_ACEITE_CONFORME] AS
SELECT -- e.DES_MATERIAL, c.DES_CENTRO1,
t.ID_TIEMPO, ID_TEMP_PESCA = (SELECT TOP 1 TP.ID_TEMP_PESCA FROM VD_TEMPORADA_PESCA TP WHERE t.FECH_DIA_SAP BETWEEN TP.FEC_INICIO AND TP.FEC_FIN),
e.ID_MATERIAL, c.ID_CENTRO,
SUM(CASE WHEN b.QM_ACIDEZ <= 3 AND b.QM_IND_ANISIDINA <= 20 THEN a.VAL_PRODUCCION
	ELSE 0 END) VAL_PROD_CUMPLE, -- Acidez < 3 Anisidina < 20
SUM(a.VAL_PRODUCCION) VAL_PRODUCCION, SP_P_AJUSTADO = 4,448.115, TN_PRODUCIDAS_AJUSTADO = 4,631.725 -- 88169.93 96439.66
FROM VF_PRODUCCION a (NOLOCK)
INNER JOIN (
	SELECT ID_LOTE, CAST(QM_ACIDEZ AS DECIMAL(8,4)) QM_ACIDEZ, CAST(QM_IND_ANISIDINA AS DECIMAL(8,4)) QM_IND_ANISIDINA FROM VD_LOTES_ACEITE a (NOLOCK) WHERE ISNUMERIC(QM_ACIDEZ) = 1 AND ISNUMERIC(QM_IND_ANISIDINA) = 1	
) b ON a.ID_LOTE = b.ID_LOTE
INNER JOIN VD_CENTRO_MM c (NOLOCK) ON a.ID_CENTRO = c.ID_CENTRO
INNER JOIN VD_MEDIDA d (NOLOCK) ON a.ID_MEDIDA = d.ID_MEDIDA
INNER JOIN VD_MATERIAL e (NOLOCK) ON a.ID_MATERIAL = e.ID_MATERIAL
INNER JOIN VD_TIEMPO t (NOLOCK) ON a.ID_TIEMPO = t.ID_TIEMPO
WHERE d.DES_MEDIDA = 'TM'
-- AND t.ID_TIEMPO between 4170 and 4262
AND e.DES_MATERIAL in ('ACEITE DE PROCESO','ACEITE DE RECUPERACIÓN SECUNDARIA')
AND ISNUMERIC(b.QM_IND_ANISIDINA) = 1 AND ISNUMERIC(b.QM_ACIDEZ) = 1
GROUP BY t.ID_TIEMPO,e.ID_MATERIAL, c.ID_CENTRO, FECH_DIA_SAP
-- ORDER BY 1

GO

/*IF OBJECT_ID('tempdb..#VD_LOTES_ACEITE') IS NOT NULL
DROP TABLE #VD_LOTES_ACEITE

CREATE TABLE #VD_LOTES_ACEITE
(ID_LOTE INT,
QM_ACIDEZ DECIMAL (8,4),
QM_IND_ANISIDINA DECIMAL (8,4))

INSERT INTO #VD_LOTES_ACEITE -- select * from #VD_LOTES_ACEITE
SELECT ID_LOTE, QM_ACIDEZ, QM_IND_ANISIDINA FROM VD_LOTES_ACEITE a (NOLOCK) WHERE ISNUMERIC(QM_ACIDEZ) = 1 AND ISNUMERIC(QM_IND_ANISIDINA) = 1

SELECT e.DES_MATERIAL, c.DES_CENTRO1,
SUM(CASE WHEN b.QM_ACIDEZ <= 3 AND b.QM_IND_ANISIDINA <= 20 THEN a.VAL_PRODUCCION
	ELSE 0 END) VAL_PROD_CUMPLE, -- Acidez < 3 Anisidina < 20
SUM(a.VAL_PRODUCCION) VAL_PRODUCCION, SP_P_AJUSTADO = 88.17, TN_PRODUCIDAS_AJUSTADO = 96.44
FROM VF_PRODUCCION a (NOLOCK)
INNER JOIN #VD_LOTES_ACEITE b (NOLOCK) ON a.ID_LOTE = b.ID_LOTE
INNER JOIN VD_CENTRO_MM c (NOLOCK) ON a.ID_CENTRO = c.ID_CENTRO
INNER JOIN VD_MEDIDA d (NOLOCK) ON a.ID_MEDIDA = d.ID_MEDIDA
INNER JOIN VD_MATERIAL e (NOLOCK) ON a.ID_MATERIAL = e.ID_MATERIAL
INNER JOIN VD_TIEMPO t (NOLOCK) ON a.ID_TIEMPO = t.ID_TIEMPO
WHERE d.DES_MEDIDA = 'TM'
AND t.ID_TIEMPO between 4170 and 4262
AND e.DES_MATERIAL in ('ACEITE DE PROCESO','ACEITE DE RECUPERACIÓN SECUNDARIA')
AND ISNUMERIC(b.QM_IND_ANISIDINA) = 1 AND ISNUMERIC(b.QM_ACIDEZ) = 1
GROUP BY e.DES_MATERIAL, c.DES_CENTRO1
ORDER BY 1*/




--

SELECT * -- VAL_CONSUMO_MP
FROM VF_CONSUMOS (NOLOCK)

select top 1000 * from VF_PRODUCCION (nolock) --.VAL_PRODUCCION (Double)
select top 1000 * from VD_LOTES_ACEITE (nolock)
select * from VD_MATERIAL
select * from VD_MEDIDA

select * from VD_TEMPORADA_PESCA
select * from VD_TIEMPO




