ALTER PROCEDURE [dbo].[USP_STG_PRD_TRAZABILIDAD_ETAPA1]       -- exec USP_STG_PRD_TRAZABILIDAD_ETAPA1 
        
AS SET NOCOUNT ON         
BEGIN        
        
--TRAZABILIDAD        
        
--TEMPORAL HARINA        
        
select distinct a.MANDT, a.MATNR          
into #HARINA        
from dbo.MATERIAL a         -- from STAGE_SAP_PRD.dbo.MATERIAL a        
where MATKL = '002.010'        
        
select distinct MBLNR,WERKS_I,BUDAT,BWART_I, MATNR_I, CHARG_I,SHKZG_I,MEINS_I,MENGE_I,        
MJAHR_I,ZEILE_I         
into #PT        
from DOCUMENTO_MATERIAL A        
INNER JOIN #HARINA B ON A.MANDT=B.MANDT AND A.MATNR_I=B.MATNR        
where        
BWART_I='131'        
and LGORT_I = '1150'        
--and WERKS_I='H101'         
and SUBSTRING(BUDAT,1,4)>=2013        
        
--QUITANDO ANULADOS        
        
SELECT MANDT_I,SJAHR_I,SMBLN_I,SMBLP_I         
INTO #ANULADOS        
FROM DOCUMENTO_MATERIAL A        
INNER JOIN #HARINA B ON A.MANDT=B.MANDT AND A.MATNR_I=B.MATNR        
where        
BWART_I=('132')        
and LGORT_I = '1150'        
        
SELECT A.MBLNR,A.WERKS_I,A.BUDAT,A.BWART_I,A.MATNR_I,A.CHARG_I,A.SHKZG_I,A.MEINS_I,A.MENGE_I,        
A.MJAHR_I,A.ZEILE_I         
INTO #SIN_ANULADOS        
FROM #PT A        
WHERE NOT EXISTS(SELECT 1 FROM #ANULADOS B WHERE A.MBLNR=B.SMBLN_I AND A.MJAHR_I=B.SJAHR_I AND A.ZEILE_I=B.SMBLP_I)        
        
--ASOCIACION RUMA - LOTES M        
        
SELECT DISTINCT         
a.MANDT,        
b.MATNR_I as Material_PT,         
b.CHARG_I as Lote_PT,         
a.MATNR_I as Material_MP,      
convert(datetime,a.BUDAT) as Fecha_Consumo_M,         
a.CHARG_I as Lote_M,        
b.WERKS_I,      
convert(datetime,b.BUDAT)as BUDAT,      
b.MEINS_I,      
SUM(a.MENGE_I)AS CONSUMO_M,      
SUM(b.MENGE_I)AS PRODUCCION        
INTO #RUMA_LOTEM        
from DOCUMENTO_MATERIAL a        
inner join #SIN_ANULADOS b on a.MBLNR = b.MBLNR        
where a.MATNR_I = '000000000016000000'        
--AND b.CHARG_I in('H105130340','H105130341')        
GROUP BY MANDT,b.MATNR_I,b.CHARG_I,a.MATNR_I,a.CHARG_I,a.BUDAT,      
b.WERKS_I,convert(datetime,a.BUDAT),convert(datetime,b.BUDAT),b.MEINS_I        
        
        
--ASOCIACION LOTE M - LOTE DESCARGA (H)        
        
SELECT         
c.MANDT,        
c.BUDAT,        
c.WERKS_I,        
c.Lote_PT,        
c.Material_PT,      
c.Fecha_Consumo_M,        
c.Lote_M,        
c.Material_MP,        
c.MEINS_I,        
c.PRODUCCION,      
c.CONSUMO_M,        
a.NRO_LOTE,        
a.EMBARCA,      
b.FECHA AS FECHA_M,        
LOTE_MP AS TM_DESCARGA,      
b.TOTAL_TN as TM_DESCARGA_M        
INTO #LOTE_PT_M_H        
from PROCESO_DETALLE a        
inner join PROCESO_CABECERA b on a.MANDT = b.MANDT and a.COD_PRO = b.COD_PRO         
inner join #RUMA_LOTEM c on a.MANDT = c.MANDT and rtrim(ltrim(b.MATERIAL)) = c.Material_MP         
and b.LOTE=c.Lote_M        
where a.[STATUS] = 'S'         
      
--ASOCIACION CON INFORMES DE FLOTA        
        
CREATE TABLE #INFORMES_FLOTA        
(        
MANDT VARCHAR(6)COLLATE SQL_Latin1_General_CP850_BIN2 NULL,        
BLDAT DATETIME NOT NULL,        
WERKS_I CHAR(4)COLLATE SQL_Latin1_General_CP850_BIN2 NULL,        
LOTE_PT VARCHAR(10)COLLATE SQL_Latin1_General_CP850_BIN2 NULL,        
MATERIAL_PT varchar(18)COLLATE SQL_Latin1_General_CP850_BIN2 NULL,      
FECHA_CONSUMO_M DATETIME NULL,        
LOTE_M varchar(18)COLLATE SQL_Latin1_General_CP850_BIN2 NULL,        
MATERIAL_MP varchar(18)COLLATE SQL_Latin1_General_CP850_BIN2 NULL,        
MEINS_I varchar(3)COLLATE SQL_Latin1_General_CP850_BIN2 NULL,        
MENGE_I numeric(20,4)NULL,        
NRO_LOTE varchar(10)COLLATE SQL_Latin1_General_CP850_BIN2 NULL,        
EMBARCA varchar(40)COLLATE SQL_Latin1_General_CP850_BIN2 NULL,        
TM_DESCARGA numeric(20,4)NULL,        
NUMINF varchar(6) COLLATE SQL_Latin1_General_CP850_BIN2 NULL,        
TIPINF varchar(1) COLLATE SQL_Latin1_General_CP850_BIN2 NULL,        
[STATUS] varchar(3) COLLATE SQL_Latin1_General_CP850_BIN2 NULL,        
OBJEK_H varchar(60)COLLATE SQL_Latin1_General_CP850_BIN2 NULL,        
TIPO_H CHAR(1)COLLATE SQL_Latin1_General_CP850_BIN2 NULL,      
FECHA_M VARCHAR(8)NULL,      
TM_DESCARGA_M numeric(20,4)null,      
CONSUMO_M numeric(20,4)null)        
        
---PROPIO        
INSERT INTO #INFORMES_FLOTA         
SELECT         
C.MANDT,C.BUDAT,        
C.WERKS_I,C.Lote_PT,C.Material_PT,C.Fecha_Consumo_M,C.Lote_M,        
C.Material_MP,C.MEINS_I,C.PRODUCCION,C.NRO_LOTE,        
C.EMBARCA,C.TM_DESCARGA,        
A.NUMINF, A.TIPINF, A.[STATUS],         
(rtrim(ltrim(A.MATNR)) + rtrim(ltrim(B.CHARG))) as OBJEK_H, 'H',      
C.FECHA_M,C.TM_DESCARGA_M,C.CONSUMO_M         
FROM INFORME_FLOTA A (nolock)        
inner join ORDEN_FABRICACION_DET B (nolock) on A.MANDT = B.MANDT and A.AUFNR = B.AUFNR and A.MATNR = B.MATNR        
INNER JOIN #LOTE_PT_M_H C (nolock)on A.MANDT=A.MANDT AND B.CHARG=C.NRO_LOTE        
where         
A.MANDT = '300' and A.PESCA = 'X' and DESTIN = 'CHI'        
and A.TIPINF = 'P'and A.AUFNR <> ''and A.FECDES2<>'00000000'        
        
--TERCEROS        
        
INSERT INTO #INFORMES_FLOTA        
SELECT DISTINCT      
C.MANDT,C.BUDAT,        
C.WERKS_I,C.Lote_PT,C.Material_PT,C.Fecha_Consumo_M,C.Lote_M,        
C.Material_MP,C.MEINS_I,C.PRODUCCION,C.NRO_LOTE,        
C.EMBARCA,C.TM_DESCARGA,        
A.NUMINF, A.TIPINF, A.[STATUS],         
(rtrim(ltrim(A.MATNR)) + rtrim(ltrim(B.CHARG))) as OBJEK_H, 'H',      
C.FECHA_M,C.TM_DESCARGA_M,C.CONSUMO_M         
FROM INFORME_FLOTA A (nolock)        
INNER JOIN REPARTO_PLAN_ENTREGA B (nolock) on A.MANDT = B.MANDT and A.EBELN = B.EBELN        
INNER JOIN #LOTE_PT_M_H C (nolock)on A.MANDT=A.MANDT AND B.CHARG=C.NRO_LOTE        
where A.MANDT = '300' and A.PESCA = 'X' and DESTIN = 'CHI'        
and A.TIPINF = 'T'and A.EBELN <> ''and A.FECDES2<>'00000000'        
        
--DATOS DE SECCION 1        

SELECT
H.MANDT,         
H.BLDAT,H.WERKS_I,H.LOTE_PT,        
H.MATERIAL_PT,H.FECHA_CONSUMO_M,H.LOTE_M,H.MATERIAL_MP,H.MEINS_I,        
H.MENGE_I,H.NRO_LOTE,H.EMBARCA,H.TM_DESCARGA,H.NUMINF,H.TIPINF,H.[STATUS],H.OBJEK_H,H.TIPO_H        
PP_EMBARCACION, PP_HABIL_CHD,PP_RSW, PP_TEMPERATURA, PP_ZONA_PESCA,        
PP_PRESEN_COMBUSTIBLE,PP_MATERIAL_EXTRANO,PP_CHATA,PP_TOLVA,        
PP_POZA1,PP_POZA2,PP_POZA3,PP_POZA4,PP_POZA5,PP_POZA6,PP_POZA7,        
PP_POZA8,PP_POZA9,PP_POZA10,PP_DESCARGA_TM_H,QM_LONG_MIN,QM_LONG_MAX,        
QM_LONG_PROMEDIO, 
QM_EST_SEX_II,        
QM_EST_SEX_III,        
QM_EST_SEX_IV,QM_EST_SEX_V,QM_EST_SEX_VI,        
QM_HEMBRAS, 
QM_DESTROZO,
PP_ACEITE_CAT_FRESCO,
CONVERT(DATETIME,PP_FECINI_DESCARGA)AS FECHA_INICIO_DESCARGA,        
CONVERT(DATETIME,PP_FECFIN_DESCARGA)AS FECHA_FINAL_DESCARGA,        
PP_HR_INI_DESCARGA,        
PP_HR_FIN_DESCARGA,
H.TM_DESCARGA AS DESCARGA_M,      
H.FECHA_M,      
H.TM_DESCARGA_M,H.CONSUMO_M,      
QM_HOR_INI_RUM=NULL,      
QM_HOR_FIN_RUM=NULL,    
QM_NUM_NOTIF_1=null
INTO #INFORME_CALIDAD    -- drop table #INFORME_CALIDAD     -- select * from #INFORME_CALIDAD 
FROM SECCION_1 A        
INNER JOIN #INFORMES_FLOTA H on RTRIM(LTRIM(A.MANDT)) = RTRIM(LTRIM(H.MANDT))   
   and RTRIM(LTRIM(A.MATERIAL_LOTE)) =RTRIM(LTRIM(H.OBJEK_H))

alter table #INFORME_CALIDAD add QM_PESO_PROMEDIO	varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2		
alter table #INFORME_CALIDAD add QM_MODA			varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2					
alter table #INFORME_CALIDAD add QM_JUVENILES		varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2		
alter table #INFORME_CALIDAD add PP_ESPECIE_ACOMPANANTE	varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2
alter table #INFORME_CALIDAD add PP_HUMEDAD			varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2	
alter table #INFORME_CALIDAD add PP_GRASA			varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2		
alter table #INFORME_CALIDAD add PP_SALES			varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2			
alter table #INFORME_CALIDAD add PP_ACEITE_TDC		varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2	
alter table #INFORME_CALIDAD add QM_TBVN			varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2			
alter table #INFORME_CALIDAD add PP_ESPECIE_INCIDENT	varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2	
alter table #INFORME_CALIDAD add QM_HOR_INI_PRO			varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2
alter table #INFORME_CALIDAD add QM_HOR_FIN_PRO		varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2	
alter table #INFORME_CALIDAD add QM_CAL_POT_MP		varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2	

alter table #INFORME_CALIDAD add MAT_LOT varchar(28) COLLATE SQL_Latin1_General_CP850_BIN2
update #INFORME_CALIDAD set MAT_LOT = MATERIAL_MP+LOTE_M -- select MAT_LOT,MATERIAL_MP,LOTE_M from #INFORMES_FLOTA

CREATE INDEX INX_MAT_LOT ON #INFORME_CALIDAD (MAT_LOT)

update H set
QM_PESO_PROMEDIO=			x.QM_PESO_PROMEDIO,  
QM_MODA=					x.QM_MODA,
QM_JUVENILES=				x.QM_JUVENILES,
PP_ESPECIE_ACOMPANANTE=		x.PP_ESPECIE_ACOMPANANTE,
PP_HUMEDAD=					x.PP_HUMEDAD,
PP_GRASA=					x.PP_GRASA,
PP_SALES=					x.PP_SALES,
PP_ACEITE_TDC=				x.PP_ACEITE_TDC,
QM_TBVN=					x.QM_TBVN,
PP_ESPECIE_INCIDENT=		x.PP_ESPECIE_INCIDENT,
QM_HOR_INI_PRO=				x.QM_HOR_INI_PRO,
QM_HOR_FIN_PRO=				x.QM_HOR_FIN_PRO,
QM_CAL_POT_MP=				x.QM_CAL_POT_MP 
FROM SECCION_1 x INNER JOIN #INFORME_CALIDAD H ON H.MAT_LOT=x.MATERIAL_LOTE -- select * from #INFORME_CALIDAD

alter table #INFORME_CALIDAD add SD_CLASI_COMERCIAL		varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2	
alter table #INFORME_CALIDAD add PROTEINA_DUMAS			varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2	
alter table #INFORME_CALIDAD add GRASA					varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2	
alter table #INFORME_CALIDAD add HUMEDAD				varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2	
alter table #INFORME_CALIDAD add CENIZA					varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2	
alter table #INFORME_CALIDAD add ANTIOXIDANTE			varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2	
alter table #INFORME_CALIDAD add SAL					varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2	
alter table #INFORME_CALIDAD add ARENA					varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2	
alter table #INFORME_CALIDAD add TBVN					varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2	
alter table #INFORME_CALIDAD add HISTAMINA				varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2	
alter table #INFORME_CALIDAD add FFA					varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2	
alter table #INFORME_CALIDAD add PROTEINA_S3			varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2	
alter table #INFORME_CALIDAD add HUMEDAD_S3				varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2	
alter table #INFORME_CALIDAD add GRANULOMETRIA			varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2	
alter table #INFORME_CALIDAD add DENSIDAD_COMP			varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2	
alter table #INFORME_CALIDAD add TBVN_S3				varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2	
alter table #INFORME_CALIDAD add GRASA_S3				varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2	
alter table #INFORME_CALIDAD add DENSIDAD_APARENTE		varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2	
alter table #INFORME_CALIDAD add NUMERO_FLUJO			varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2	
alter table #INFORME_CALIDAD add QM_SHIGUELLA			varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2	
alter table #INFORME_CALIDAD add QM_SALMONELLA			varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2	
alter table #INFORME_CALIDAD add QM_SALMONELLA02		varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2	
alter table #INFORME_CALIDAD add QM_SALMONELLA03		varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2	
alter table #INFORME_CALIDAD add QM_SALMONELLA04		varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2	
alter table #INFORME_CALIDAD add QM_SALMONELLA05		varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2	
alter table #INFORME_CALIDAD add QM_SALMONELLA06		varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2	
alter table #INFORME_CALIDAD add QM_SALMONELLA07		varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2	
alter table #INFORME_CALIDAD add QM_ENTEROBACTERIA		varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2	
alter table #INFORME_CALIDAD add QM_ENTEROBACTERIA02	varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2	
alter table #INFORME_CALIDAD add QM_ENTEROBACTERIA03	varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2	
alter table #INFORME_CALIDAD add QM_ENTEROBACTERIA04	varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2	
alter table #INFORME_CALIDAD add QM_ENTEROBACTERIA05	varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2	
alter table #INFORME_CALIDAD add QM_ENTEROBACTERIA06	varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2	
alter table #INFORME_CALIDAD add QM_ENTEROBACTERIA07	varchar(60) COLLATE SQL_Latin1_General_CP850_BIN2	

update H set
SD_CLASI_COMERCIAL		=x.SD_CLASI_COMERCIAL	,
PROTEINA_DUMAS			=x.QM_PROTEINA_DUMAS	,
GRASA					=x.QM_GRASA				,
HUMEDAD					=x.QM_HUMEDAD			,
CENIZA					=x.QM_ASH				,
ANTIOXIDANTE			=x.QM_ANTIOXIDANTE		,
SAL						=x.QM_ARENA_SAL			,
ARENA					=x.QM_ARENA				,
TBVN					=x.QM_TBVN				,
HISTAMINA				=x.QM_HISTAMIN			,
FFA						=x.QM_FFA				,
PROTEINA_S3				=x.QM_PROTEINA_S3		,
HUMEDAD_S3				=x.QM_HUMEDAD_S3		,
GRANULOMETRIA			=x.QM_GRANULOMETRIA		,
DENSIDAD_COMP			=x.QM_DENSIDAD_COMP		,
TBVN_S3					=x.QM_TVBN_S3			,
GRASA_S3				=x.QM_GRASA_S3			,
DENSIDAD_APARENTE		=x.QM_DENS_APARENTE		,
NUMERO_FLUJO			=x.QM_NUM_FLUJO			,
QM_SHIGUELLA			=x.QM_SHIGUELLA			,
QM_SALMONELLA			=x.QM_SALMONELLA		,
QM_SALMONELLA02			=x.QM_SALMONELLA02		,
QM_SALMONELLA03			=x.QM_SALMONELLA03		,
QM_SALMONELLA04			=x.QM_SALMONELLA04		,
QM_SALMONELLA05			=x.QM_SALMONELLA05		,
QM_SALMONELLA06			=x.QM_SALMONELLA06		,
QM_SALMONELLA07			=x.QM_SALMONELLA07		,
QM_ENTEROBACTERIA		=x.QM_ENTEROBACTERIA	,
QM_ENTEROBACTERIA02		=x.QM_ENTEROBACTERIA02	,
QM_ENTEROBACTERIA03		=x.QM_ENTEROBACTERIA03	,
QM_ENTEROBACTERIA04		=x.QM_ENTEROBACTERIA04	,
QM_ENTEROBACTERIA05		=x.QM_ENTEROBACTERIA05	,
QM_ENTEROBACTERIA06		=x.QM_ENTEROBACTERIA06	,
QM_ENTEROBACTERIA07		=x.QM_ENTEROBACTERIA07	
FROM CARACTERISTICAS_SECCION3 x INNER JOIN #INFORME_CALIDAD H -- select * from #INFORME_CALIDAD
ON H.MATERIAL_PT=LEFT(RTRIM(ltrim(x.COD_MATERIAL_LOTE)),18) AND H.LOTE_PT=RIGHT(RTRIM(ltrim(x.COD_MATERIAL_LOTE)),10)    
 
/*
-- BACK UP     
SELECT        
H.MANDT,         
H.BLDAT,H.WERKS_I,H.LOTE_PT,        
H.MATERIAL_PT,H.FECHA_CONSUMO_M,H.LOTE_M,H.MATERIAL_MP,H.MEINS_I,        
H.MENGE_I,H.NRO_LOTE,H.EMBARCA,H.TM_DESCARGA,H.NUMINF,H.TIPINF,H.[STATUS],H.OBJEK_H,H.TIPO_H        
PP_EMBARCACION, PP_HABIL_CHD,PP_RSW, PP_TEMPERATURA, PP_ZONA_PESCA,        
PP_PRESEN_COMBUSTIBLE,PP_MATERIAL_EXTRANO,PP_CHATA,PP_TOLVA,        
PP_POZA1,PP_POZA2,PP_POZA3,PP_POZA4,PP_POZA5,PP_POZA6,PP_POZA7,        
PP_POZA8,PP_POZA9,PP_POZA10,PP_DESCARGA_TM_H,QM_LONG_MIN,QM_LONG_MAX,        
QM_LONG_PROMEDIO,        
QM_PESO_PROMEDIO=(SELECT TOP 1 QM_PESO_PROMEDIO FROM SECCION_1 X WHERE (H.MATERIAL_MP+H.LOTE_M)=X.MATERIAL_LOTE),        
QM_MODA=(SELECT TOP 1 QM_MODA FROM SECCION_1 X WHERE (H.MATERIAL_MP+H.LOTE_M)=X.MATERIAL_LOTE),        
QM_JUVENILES=(SELECT TOP 1 QM_JUVENILES FROM SECCION_1 X WHERE (H.MATERIAL_MP+H.LOTE_M)=X.MATERIAL_LOTE),        
PP_ESPECIE_ACOMPANANTE=(SELECT TOP 1 PP_ESPECIE_ACOMPANANTE FROM SECCION_1 X WHERE (H.MATERIAL_MP+H.LOTE_M)=X.MATERIAL_LOTE),        
QM_EST_SEX_II,        
QM_EST_SEX_III,        
QM_EST_SEX_IV,QM_EST_SEX_V,QM_EST_SEX_VI,        
QM_HEMBRAS,      
PP_HUMEDAD=(SELECT TOP 1 PP_HUMEDAD FROM SECCION_1 X WHERE (H.MATERIAL_MP+H.LOTE_M)=X.MATERIAL_LOTE),      
PP_GRASA=(SELECT TOP 1 PP_GRASA FROM SECCION_1 X WHERE (H.MATERIAL_MP+H.LOTE_M)=X.MATERIAL_LOTE),      
PP_SALES=(SELECT TOP 1 PP_SALES FROM SECCION_1 X WHERE (H.MATERIAL_MP+H.LOTE_M)=X.MATERIAL_LOTE),      
QM_DESTROZO,        
PP_ACEITE_TDC=(SELECT TOP 1 PP_ACEITE_TDC FROM SECCION_1 X WHERE (H.MATERIAL_MP+H.LOTE_M)=X.MATERIAL_LOTE),        
QM_TBVN=(SELECT TOP 1 QM_TBVN FROM SECCION_1 X WHERE (H.MATERIAL_MP+H.LOTE_M)=X.MATERIAL_LOTE),        
PP_ACEITE_CAT_FRESCO,        
CONVERT(DATETIME,PP_FECINI_DESCARGA)AS FECHA_INICIO_DESCARGA,        
CONVERT(DATETIME,PP_FECFIN_DESCARGA)AS FECHA_FINAL_DESCARGA,        
PP_HR_INI_DESCARGA,        
PP_HR_FIN_DESCARGA,        
PP_ESPECIE_INCIDENT=(SELECT TOP 1 PP_ESPECIE_INCIDENT FROM SECCION_1 X WHERE (H.MATERIAL_MP+H.LOTE_M)=X.MATERIAL_LOTE),      
QM_HOR_INI_PRO=(SELECT TOP 1 QM_HOR_INI_PRO FROM SECCION_1 G WHERE (H.MATERIAL_MP+H.LOTE_M)=G.MATERIAL_LOTE),      
QM_HOR_FIN_PRO=(SELECT TOP 1 QM_HOR_FIN_PRO FROM SECCION_1 W WHERE (H.MATERIAL_MP+H.LOTE_M)=W.MATERIAL_LOTE),      
QM_CAL_POT_MP=(SELECT TOP 1 QM_CAL_POT_MP FROM SECCION_1 K WHERE (H.MATERIAL_MP+H.LOTE_M)=K.MATERIAL_LOTE),      
H.TM_DESCARGA AS DESCARGA_M,      
H.FECHA_M,      
H.TM_DESCARGA_M,H.CONSUMO_M,      
QM_HOR_INI_RUM=NULL,      
QM_HOR_FIN_RUM=NULL,      
SD_CLASI_COMERCIAL=(SELECT TOP 1 SD_CLASI_COMERCIAL FROM CARACTERISTICAS_SECCION3 JH       
WHERE H.MATERIAL_PT=LEFT(RTRIM(ltrim(JH.COD_MATERIAL_LOTE)),18) AND H.LOTE_PT=RIGHT(RTRIM(ltrim(JH.COD_MATERIAL_LOTE)),10)),      
PROTEINA_DUMAS=(SELECT TOP 1 QM_PROTEINA_DUMAS FROM CARACTERISTICAS_SECCION3 J      
WHERE H.MATERIAL_PT=LEFT(RTRIM(ltrim(J.COD_MATERIAL_LOTE)),18) AND H.LOTE_PT=RIGHT(RTRIM(ltrim(J.COD_MATERIAL_LOTE)),10)),      
GRASA=(SELECT TOP 1 QM_GRASA FROM CARACTERISTICAS_SECCION3 Q      
WHERE H.MATERIAL_PT=LEFT(RTRIM(ltrim(Q.COD_MATERIAL_LOTE)),18) AND H.LOTE_PT=RIGHT(RTRIM(ltrim(Q.COD_MATERIAL_LOTE)),10)),      
HUMEDAD=(SELECT TOP 1 QM_HUMEDAD FROM CARACTERISTICAS_SECCION3 IH       
WHERE H.MATERIAL_PT=LEFT(RTRIM(ltrim(IH.COD_MATERIAL_LOTE)),18) AND H.LOTE_PT=RIGHT(RTRIM(ltrim(IH.COD_MATERIAL_LOTE)),10)),      
CENIZA=(SELECT TOP 1 QM_ASH FROM CARACTERISTICAS_SECCION3 TH       
WHERE H.MATERIAL_PT=LEFT(RTRIM(ltrim(TH.COD_MATERIAL_LOTE)),18) AND H.LOTE_PT=RIGHT(RTRIM(ltrim(TH.COD_MATERIAL_LOTE)),10)),      
ANTIOXIDANTE=(SELECT TOP 1 QM_ANTIOXIDANTE FROM CARACTERISTICAS_SECCION3 ZH       
WHERE H.MATERIAL_PT=LEFT(RTRIM(ltrim(ZH.COD_MATERIAL_LOTE)),18) AND H.LOTE_PT=RIGHT(RTRIM(ltrim(ZH.COD_MATERIAL_LOTE)),10)),      
SAL=(SELECT TOP 1 QM_ARENA_SAL FROM CARACTERISTICAS_SECCION3 W       
WHERE H.MATERIAL_PT=LEFT(RTRIM(ltrim(W.COD_MATERIAL_LOTE)),18) AND H.LOTE_PT=RIGHT(RTRIM(ltrim(W.COD_MATERIAL_LOTE)),10)),      
ARENA=(SELECT TOP 1 QM_ARENA FROM CARACTERISTICAS_SECCION3 Z       
WHERE H.MATERIAL_PT=LEFT(RTRIM(ltrim(Z.COD_MATERIAL_LOTE)),18) AND H.LOTE_PT=RIGHT(RTRIM(ltrim(Z.COD_MATERIAL_LOTE)),10)),      
TBVN=(SELECT TOP 1 QM_TBVN FROM CARACTERISTICAS_SECCION3 D       
WHERE H.MATERIAL_PT=LEFT(RTRIM(ltrim(D.COD_MATERIAL_LOTE)),18) AND H.LOTE_PT=RIGHT(RTRIM(ltrim(D.COD_MATERIAL_LOTE)),10)),      
HISTAMINA=(SELECT TOP 1 QM_HISTAMIN FROM CARACTERISTICAS_SECCION3 ZA      
WHERE H.MATERIAL_PT=LEFT(RTRIM(ltrim(ZA.COD_MATERIAL_LOTE)),18) AND H.LOTE_PT=RIGHT(RTRIM(ltrim(ZA.COD_MATERIAL_LOTE)),10)),      
FFA=(SELECT TOP 1 QM_FFA FROM CARACTERISTICAS_SECCION3 ZB      
WHERE H.MATERIAL_PT=LEFT(RTRIM(ltrim(ZB.COD_MATERIAL_LOTE)),18) AND H.LOTE_PT=RIGHT(RTRIM(ltrim(ZB.COD_MATERIAL_LOTE)),10)),      
PROTEINA_S3=(SELECT TOP 1 QM_PROTEINA_S3 FROM CARACTERISTICAS_SECCION3 ZC      
WHERE H.MATERIAL_PT=LEFT(RTRIM(ltrim(ZC.COD_MATERIAL_LOTE)),18) AND H.LOTE_PT=RIGHT(RTRIM(ltrim(ZC.COD_MATERIAL_LOTE)),10)),      
HUMEDAD_S3=(SELECT TOP 1 QM_HUMEDAD_S3 FROM CARACTERISTICAS_SECCION3 ZD      
WHERE H.MATERIAL_PT=LEFT(RTRIM(ltrim(ZD.COD_MATERIAL_LOTE)),18) AND H.LOTE_PT=RIGHT(RTRIM(ltrim(ZD.COD_MATERIAL_LOTE)),10)),      
GRANULOMETRIA=(SELECT TOP 1 QM_GRANULOMETRIA FROM CARACTERISTICAS_SECCION3 ZE      
WHERE H.MATERIAL_PT=LEFT(RTRIM(ltrim(ZE.COD_MATERIAL_LOTE)),18) AND H.LOTE_PT=RIGHT(RTRIM(ltrim(ZE.COD_MATERIAL_LOTE)),10)),      
DENSIDAD_COMP=(SELECT TOP 1 QM_DENSIDAD_COMP FROM CARACTERISTICAS_SECCION3 ZF      
WHERE H.MATERIAL_PT=LEFT(RTRIM(ltrim(ZF.COD_MATERIAL_LOTE)),18) AND H.LOTE_PT=RIGHT(RTRIM(ltrim(ZF.COD_MATERIAL_LOTE)),10)),       
TBVN_S3=(SELECT TOP 1 QM_TVBN_S3 FROM CARACTERISTICAS_SECCION3 ZG      
WHERE H.MATERIAL_PT=LEFT(RTRIM(ltrim(ZG.COD_MATERIAL_LOTE)),18) AND H.LOTE_PT=RIGHT(RTRIM(ltrim(ZG.COD_MATERIAL_LOTE)),10)),       
GRASA_S3=(SELECT TOP 1 QM_GRASA_S3 FROM CARACTERISTICAS_SECCION3 ZH      
WHERE H.MATERIAL_PT=LEFT(RTRIM(ltrim(ZH.COD_MATERIAL_LOTE)),18) AND H.LOTE_PT=RIGHT(RTRIM(ltrim(ZH.COD_MATERIAL_LOTE)),10)),       
DENSIDAD_APARENTE=(SELECT TOP 1 QM_DENS_APARENTE FROM CARACTERISTICAS_SECCION3 ZI      
WHERE H.MATERIAL_PT=LEFT(RTRIM(ltrim(ZI.COD_MATERIAL_LOTE)),18) AND H.LOTE_PT=RIGHT(RTRIM(ltrim(ZI.COD_MATERIAL_LOTE)),10)),       
NUMERO_FLUJO=(SELECT TOP 1 QM_NUM_FLUJO FROM CARACTERISTICAS_SECCION3 ZJ      
WHERE H.MATERIAL_PT=LEFT(RTRIM(ltrim(ZJ.COD_MATERIAL_LOTE)),18) AND H.LOTE_PT=RIGHT(RTRIM(ltrim(ZJ.COD_MATERIAL_LOTE)),10)),       
QM_NUM_NOTIF_1=null,    
QM_SHIGUELLA=(SELECT TOP 1 QM_SHIGUELLA FROM CARACTERISTICAS_SECCION3 CS    
WHERE H.MATERIAL_PT=LEFT(RTRIM(ltrim(CS.COD_MATERIAL_LOTE)),18) AND H.LOTE_PT=RIGHT(RTRIM(ltrim(CS.COD_MATERIAL_LOTE)),10)),    
QM_SALMONELLA=(SELECT TOP 1 QM_SALMONELLA FROM CARACTERISTICAS_SECCION3 DS    
WHERE H.MATERIAL_PT=LEFT(RTRIM(ltrim(DS.COD_MATERIAL_LOTE)),18) AND H.LOTE_PT=RIGHT(RTRIM(ltrim(DS.COD_MATERIAL_LOTE)),10)),    
QM_SALMONELLA02=(SELECT TOP 1 QM_SALMONELLA02 FROM CARACTERISTICAS_SECCION3 ES    
WHERE H.MATERIAL_PT=LEFT(RTRIM(ltrim(ES.COD_MATERIAL_LOTE)),18) AND H.LOTE_PT=RIGHT(RTRIM(ltrim(ES.COD_MATERIAL_LOTE)),10)),    
QM_SALMONELLA03=(SELECT TOP 1 QM_SALMONELLA03 FROM CARACTERISTICAS_SECCION3 FS    
WHERE H.MATERIAL_PT=LEFT(RTRIM(ltrim(FS.COD_MATERIAL_LOTE)),18) AND H.LOTE_PT=RIGHT(RTRIM(ltrim(FS.COD_MATERIAL_LOTE)),10)),    
QM_SALMONELLA04=(SELECT TOP 1 QM_SALMONELLA04 FROM CARACTERISTICAS_SECCION3 GS    
WHERE H.MATERIAL_PT=LEFT(RTRIM(ltrim(GS.COD_MATERIAL_LOTE)),18) AND H.LOTE_PT=RIGHT(RTRIM(ltrim(GS.COD_MATERIAL_LOTE)),10)),    
QM_SALMONELLA05=(SELECT TOP 1 QM_SALMONELLA05 FROM CARACTERISTICAS_SECCION3 HS    
WHERE H.MATERIAL_PT=LEFT(RTRIM(ltrim(HS.COD_MATERIAL_LOTE)),18) AND H.LOTE_PT=RIGHT(RTRIM(ltrim(HS.COD_MATERIAL_LOTE)),10)),    
QM_SALMONELLA06=(SELECT TOP 1 QM_SALMONELLA06 FROM CARACTERISTICAS_SECCION3 JS    
WHERE H.MATERIAL_PT=LEFT(RTRIM(ltrim(JS.COD_MATERIAL_LOTE)),18) AND H.LOTE_PT=RIGHT(RTRIM(ltrim(JS.COD_MATERIAL_LOTE)),10)),    
QM_SALMONELLA07=(SELECT TOP 1 QM_SALMONELLA07 FROM CARACTERISTICAS_SECCION3 KS    
WHERE H.MATERIAL_PT=LEFT(RTRIM(ltrim(KS.COD_MATERIAL_LOTE)),18) AND H.LOTE_PT=RIGHT(RTRIM(ltrim(KS.COD_MATERIAL_LOTE)),10)),    
QM_ENTEROBACTERIA=(SELECT TOP 1 QM_ENTEROBACTERIA FROM CARACTERISTICAS_SECCION3 LS    
WHERE H.MATERIAL_PT=LEFT(RTRIM(ltrim(LS.COD_MATERIAL_LOTE)),18) AND H.LOTE_PT=RIGHT(RTRIM(ltrim(LS.COD_MATERIAL_LOTE)),10)),    
QM_ENTEROBACTERIA02=(SELECT TOP 1 QM_ENTEROBACTERIA02 FROM CARACTERISTICAS_SECCION3 MS    
WHERE H.MATERIAL_PT=LEFT(RTRIM(ltrim(MS.COD_MATERIAL_LOTE)),18) AND H.LOTE_PT=RIGHT(RTRIM(ltrim(MS.COD_MATERIAL_LOTE)),10)),    
QM_ENTEROBACTERIA03=(SELECT TOP 1 QM_ENTEROBACTERIA03 FROM CARACTERISTICAS_SECCION3 NS    
WHERE H.MATERIAL_PT=LEFT(RTRIM(ltrim(NS.COD_MATERIAL_LOTE)),18) AND H.LOTE_PT=RIGHT(RTRIM(ltrim(NS.COD_MATERIAL_LOTE)),10)),    
QM_ENTEROBACTERIA04=(SELECT TOP 1 QM_ENTEROBACTERIA04 FROM CARACTERISTICAS_SECCION3 NS    
WHERE H.MATERIAL_PT=LEFT(RTRIM(ltrim(NS.COD_MATERIAL_LOTE)),18) AND H.LOTE_PT=RIGHT(RTRIM(ltrim(NS.COD_MATERIAL_LOTE)),10)),    
QM_ENTEROBACTERIA05=(SELECT TOP 1 QM_ENTEROBACTERIA05 FROM CARACTERISTICAS_SECCION3 NS    
WHERE H.MATERIAL_PT=LEFT(RTRIM(ltrim(NS.COD_MATERIAL_LOTE)),18) AND H.LOTE_PT=RIGHT(RTRIM(ltrim(NS.COD_MATERIAL_LOTE)),10)),    
QM_ENTEROBACTERIA06=(SELECT TOP 1  QM_ENTEROBACTERIA06 FROM CARACTERISTICAS_SECCION3 NS    
WHERE H.MATERIAL_PT=LEFT(RTRIM(ltrim(NS.COD_MATERIAL_LOTE)),18) AND H.LOTE_PT=RIGHT(RTRIM(ltrim(NS.COD_MATERIAL_LOTE)),10)),    
QM_ENTEROBACTERIA07=(SELECT TOP 1 QM_ENTEROBACTERIA07 FROM CARACTERISTICAS_SECCION3 NS    
WHERE H.MATERIAL_PT=LEFT(RTRIM(ltrim(NS.COD_MATERIAL_LOTE)),18) AND H.LOTE_PT=RIGHT(RTRIM(ltrim(NS.COD_MATERIAL_LOTE)),10))    
INTO #INFORME_CALIDAD        
FROM SECCION_1 A        
INNER JOIN #INFORMES_FLOTA H on RTRIM(LTRIM(A.MANDT)) = RTRIM(LTRIM(H.MANDT))   
   and RTRIM(LTRIM(A.MATERIAL_LOTE)) =RTRIM(LTRIM(H.OBJEK_H))        
 --ejecutar 
*/
--TVBN ERROR       
       
--TOMANDO COORDENADAS GEOGRAFICAS         
        
SELECT MANDT,NUMINF,NUMCALA,TBODE,LATGRA,LATMIN,LONGRA,LONMIN,        
ROW_NUMBER() OVER(PARTITION BY NUMINF ORDER BY TBODE DESC)AS ORDEN         
INTO #ORDEN_CALAS        
FROM CALAS        
WHERE NUMINF<>''        
        
--CALAS         
SELECT MANDT,NUMINF,NUMCALA,TBODE,LATGRA,LATMIN,LONGRA,LONMIN         
INTO #CALAS        
FROM #ORDEN_CALAS        
WHERE ORDEN=1        
        
--AGREGANDO CAMPOS DEL INFORME DE FLOTA        
        
SELECT        
B.WERKS_I AS COD_PLANTA,D.NAME2 AS PLANTA,        
B.BLDAT AS FECHA_PRODUCCION,        
B.LOTE_PT,        
B.MATERIAL_PT,       
B.FECHA_CONSUMO_M,       
B.LOTE_M,        
B.MATERIAL_MP,B.MEINS_I,B.MENGE_I as CANTIDAD_SACOS,        
B.NRO_LOTE,B.OBJEK_H,B.NUMINF,        
A.MATRICULA as CODIGO_EMBARCACION,        
A.EMBARC as EMBARCACION,        
C.TPRESEV AS CONSERVACION,        
CASE WHEN left(rtrim(ltrim(A.HORDES2)),4) between '0001' and '0700'         
                  then convert(varchar(8),         
convert(datetime,A.FECDES2) - 1, 112) else A.FECDES2 end AS FECHA,        
A.TIPINF as TIPO_INFORME, 

(CASE WHEN FECDES1='00000000'THEN '1900-01-01'ELSE CONVERT(DATETIME,CONVERT(CHAR(10),CONVERT (DATETIME,FECDES1),120)) END      
--CONVERT(DATETIME,CONVERT(CHAR(10),CONVERT (DATETIME,FECDES1),120)
+' '+CASE WHEN HORDES1='000000'THEN '00:00:01'ELSE
SUBSTRING(HORDES1,1,2)+':'+SUBSTRING(HORDES1,3,2)          
+':'+SUBSTRING(HORDES2,5,2)END )as FECHA_INICIO_DESCARGA,

(CASE WHEN FECDES2='00000000'THEN '1900-01-01'ELSE CONVERT(DATETIME,CONVERT(CHAR(10),CONVERT (DATETIME,FECDES2),120)) END         
--CONVERT(DATETIME,CONVERT(CHAR(10),CONVERT (DATETIME,FECDES2),120)
+' '+
CASE WHEN HORDES2='000000'THEN '00:00:01'else
SUBSTRING(HORDES2,1,2)+':'+SUBSTRING(HORDES2,3,2)          
+':'+SUBSTRING(HORDES2,5,2) end) as FECHA_FIN_DESCARGA,     
B.PP_TEMPERATURA as TEMPERATURA,        
B.PP_RSW  as SISTEMA_FRIO,        
B.PP_ZONA_PESCA as  COD_ZONA_PESCA,        
B.PP_ZONA_PESCA as  NOMBRE_ZONA_PESCA,        
A.DESTIN  as DESTINO,        
B.PP_CHATA  as CHATA,        
B.PP_TOLVA  as CODIGO_TOLVA,        
B.PP_DESCARGA_TM_H as flujo_ton_hor,        
B.PP_ESPECIE_ACOMPANANTE as especie_acomp,        
B.PP_ESPECIE_ACOMPANANTE as descespecieacomp,        
B.PP_ESPECIE_INCIDENT as especie_acomp_porc,        
B.PP_HUMEDAD as compmphumedad,        
B.PP_GRASA   as compmpgrasa,        
B.PP_SALES  as compmpsolido,         
B.PP_ACEITE_TDC as TDC,        
B.QM_TBVN    as TVBN,        
A.FECDES1 as FECHA_INICIO_DES,        
A.FECDES2 as FECHA_FIN_DES,        
TM_DECLARADO = (select sum(x1.TBODE) from CALAS x1        
        where x1.MANDT = A.MANDT and x1.NUMINF = A.NUMINF),                
B.PP_POZA1 as poza1,        
B.PP_POZA2 as poza2,        
B.PP_POZA3 as poza3,        
B.PP_POZA4 as poza4,        
B.PP_POZA5 as poza5,        
B.PP_POZA6 as poza6,        
B.PP_POZA7 as poza7,        
B.PP_POZA8 as poza8,        
B.PP_POZA9 as poza9,        
B.PP_POZA10 as poza10,        
B.QM_LONG_MIN as LONGITUD_MINIMA,        
B.QM_LONG_MAX as LONGITUD_MAXIMA,        
B.QM_LONG_PROMEDIO as LONGITUD_PROMEDIO,        
B.QM_PESO_PROMEDIO as PESO_PROMEDIO,        
B.QM_MODA as MODA_CM,        
B.QM_JUVENILES as PORCENTAJE_JUVENILES,        
TOTAL_POZA = (CASE WHEN A.TIPINF = 'P' THEN (SELECT SUM(z.IGMNG)FROM ORDEN_FABRICACION z         
     where z.MANDT=A.MANDT and z.AUFNR=A.AUFNR)        
     WHEN A.TIPINF = 'T' THEN (SELECT SUM(y.MENGE)FROM ORDEN_COMPRA_DET y         
     where y.MANDT=A.MANDT and y.EBELN=A.EBELN)        
     ELSE A.GWEMG END),        
LATGRA=(SELECT LATGRA FROM #CALAS W WHERE A.MANDT=W.MANDT AND A.NUMINF=W.NUMINF),        
LATMIN=(SELECT LATMIN FROM #CALAS Z WHERE A.MANDT=Z.MANDT AND A.NUMINF=Z.NUMINF),        
LONGRA=(SELECT LONGRA FROM #CALAS M WHERE A.MANDT=M.MANDT AND A.NUMINF=M.NUMINF),        
LONMIN=(SELECT LONMIN FROM #CALAS N WHERE A.MANDT=N.MANDT AND A.NUMINF=N.NUMINF),      
QM_HOR_INI_PRO,      
QM_HOR_FIN_PRO,      
B.QM_CAL_POT_MP,      
B.DESCARGA_M,      
B.FECHA_M,      
B.TM_DESCARGA_M,      
QM_HOR_INI_RUM,      
QM_HOR_FIN_RUM,      
B.SD_CLASI_COMERCIAL,      
B.PROTEINA_DUMAS,      
B.GRASA,      
B.HUMEDAD,      
B.CENIZA,      
B.ANTIOXIDANTE,      
B.SAL,      
B.ARENA,      
B.TBVN,      
B.HISTAMINA,      
B.FFA,      
B.PROTEINA_S3,      
B.HUMEDAD_S3,      
B.GRANULOMETRIA,      
B.DENSIDAD_COMP,      
B.TBVN_S3,      
B.GRASA_S3,      
B.DENSIDAD_APARENTE,      
B.NUMERO_FLUJO,      
B.CONSUMO_M,      
B.QM_NUM_NOTIF_1,    
B.QM_SHIGUELLA,    
B.QM_SALMONELLA,    
B.QM_SALMONELLA02,    
B.QM_SALMONELLA03,    
B.QM_SALMONELLA04,    
B.QM_SALMONELLA05,    
B.QM_SALMONELLA06,    
B.QM_SALMONELLA07,    
B.QM_ENTEROBACTERIA,    
B.QM_ENTEROBACTERIA02,    
B.QM_ENTEROBACTERIA03,    
B.QM_ENTEROBACTERIA04,    
B.QM_ENTEROBACTERIA05,    
B.QM_ENTEROBACTERIA06,    
B.QM_ENTEROBACTERIA07          
INTO #TRAZABILIDAD  
from INFORME_FLOTA A (nolock)        
INNER JOIN #INFORME_CALIDAD B on A.MANDT = B.MANDT and A.NUMINF = B.NUMINF        
INNER JOIN EMBARCACION_OFICIAL C ON A.MATRICULA=C.MATRICULA AND A.MANDT=C.MANTD        
INNER JOIN CENTRO D ON B.WERKS_I=D.WERKS AND A.MANDT=D.MANDT        
where A.MANDT ='300'        
and A.PESCA = 'X'         
and DESTIN = 'CHI' 
--AND HORDES2<>'000000'
--ORDER BY A.FECDES1 DESC

	

--ACTUALIZANDO TABLA TRAZABILIDAD        
        
UPDATE TRAZABILIDAD_ETAPA1        
SET        
COD_PLANTA=A.COD_PLANTA,        
PLANTA=A.PLANTA,        
FECHA_PRODUCCION=A.FECHA_PRODUCCION,        
LOTE_PT=A.LOTE_PT,        
MATERIAL_PT=A.MATERIAL_PT,      
FECHA_CONSUMO_M=A.FECHA_CONSUMO_M,        
LOTE_M=A.LOTE_M,        
MATERIAL_MP=A.MATERIAL_MP,        
UNIDAD_MEDIDA=A.MEINS_I,        
CANTIDAD_SACOS=A.CANTIDAD_SACOS,        
LOTE_DESCARGA=A.NRO_LOTE,        
OBJEK_H=A.OBJEK_H,        
NUMERO_INFORME=A.NUMINF,        
CODIGO_EMBARCACION=A.CODIGO_EMBARCACION,        
EMBARCACION=A.EMBARCACION,        
CONSERVACION=A.CONSERVACION,        
FECHA=A.FECHA,        
TIPO_INFORME=A.TIPO_INFORME,        
FECHA_INICIO_DESCARGA=A.FECHA_INICIO_DESCARGA,        
FECHA_FIN_DESCARGA=A.FECHA_FIN_DESCARGA,        
TEMPERATURA=A.TEMPERATURA,        
SISTEMA_FRIO=A.SISTEMA_FRIO,        
COD_ZONA_PESCA=A.COD_ZONA_PESCA,        
NOMBRE_ZONA_PESCA=A.NOMBRE_ZONA_PESCA,        
DESTINO=A.DESTINO,        
CHATA=A.CHATA,        
CODIGO_TOLVA=A.CODIGO_TOLVA,        
FLUJO_TON_HOR=A.flujo_ton_hor,        
COD_ESPECIE_ACOMP=A.especie_acomp,        
DESC_ESPECIE_ACOMP=A.descespecieacomp,        
ESPECIE_ACOMP_PORC=A.especie_acomp_porc,        
COMPMPHUMEDAD=A.compmphumedad,        
COMPMPGRASA=A.compmpgrasa,        
COMPMPSOLIDO=A.compmpsolido,        
TDC=A.TDC,        
TVBN=A.TVBN,        
FECHA_INICIO_DES=A.FECHA_INICIO_DES,        
FECHA_FIN_DES=A.FECHA_FIN_DES,        
TM_DECLARADO=A.TM_DECLARADO,        
POZA1=A.poza1,        
POZA2=A.poza2,        
POZA3=A.poza3,        
POZA4=A.poza4,        
POZA5=A.poza5,        
POZA6=A.poza6,        
POZA7=A.poza7,        
POZA8=A.poza8,        
POZA9=A.poza9,        
POZA10=A.poza10,        
LONGITUD_MINIMA=A.LONGITUD_MINIMA,        
LONGITUD_MAXIMA=A.LONGITUD_MAXIMA,        
LONGITUD_PROMEDIO=A.LONGITUD_PROMEDIO,        
PESO_PROMEDIO=A.PESO_PROMEDIO,        
MODA_CM=A.MODA_CM,        
PORCENTAJE_JUVENILES=A.PORCENTAJE_JUVENILES,        
TOTAL_POZA=A.TOTAL_POZA,        
LATGRA=A.LATGRA,        
LATMIN=A.LATMIN,        
LONGRA=A.LONGRA,        
LONMIN=A.LONMIN,      
QM_HOR_INI_PRO=A.QM_HOR_INI_PRO,      
QM_HOR_FIN_PRO=A.QM_HOR_FIN_PRO,      
QM_CAL_POT_MP=A.QM_CAL_POT_MP,      
DESCARGA_M=A.DESCARGA_M,      
FECHA_M=A.FECHA_M,      
TM_DESCARGA_M=A.TM_DESCARGA_M,      
QM_HOR_INI_RUM=A.QM_HOR_INI_RUM,      
QM_HOR_FIN_RUM=A.QM_HOR_FIN_RUM,      
SD_CLASI_COMERCIAL=A.SD_CLASI_COMERCIAL,      
PROTEINA_DUMAS=A.PROTEINA_DUMAS,      
GRASA=A.GRASA,      
HUMEDAD=A.HUMEDAD,      
CENIZA=A.CENIZA,      
ANTIOXIDANTE=A.ANTIOXIDANTE,      
SAL=A.SAL,      
ARENA=A.ARENA,      
TBVN=A.TBVN,      
HISTAMINA=A.HISTAMINA,      
FFA=A.FFA,      
PROTEINA_S3=A.PROTEINA_S3,      
HUMEDAD_S3=A.HUMEDAD_S3,      
GRANULOMETRIA=A.GRANULOMETRIA,      
DENSIDAD_COMP=A.DENSIDAD_COMP,      
TBVN_S3=A.TBVN_S3,      
GRASA_S3=A.GRASA_S3,      
DENSIDAD_APARENTE=A.DENSIDAD_APARENTE,      
NUMERO_FLUJO=A.NUMERO_FLUJO,      
CONSUMO_M=A.CONSUMO_M,    
QM_SHIGUELLA=A.QM_SHIGUELLA,    
QM_SALMONELLA=A.QM_SALMONELLA,    
QM_SALMONELLA02=A.QM_SALMONELLA02,    
QM_SALMONELLA03=A.QM_SALMONELLA03,    
QM_SALMONELLA04=A.QM_SALMONELLA04,    
QM_SALMONELLA05=A.QM_SALMONELLA05,    
QM_SALMONELLA06=A.QM_SALMONELLA06,    
QM_SALMONELLA07=A.QM_SALMONELLA07,    
QM_ENTEROBACTERIA=A.QM_ENTEROBACTERIA,    
QM_ENTEROBACTERIA02=A.QM_ENTEROBACTERIA02,    
QM_ENTEROBACTERIA03=A.QM_ENTEROBACTERIA03,    
QM_ENTEROBACTERIA04=A.QM_ENTEROBACTERIA04,    
QM_ENTEROBACTERIA05=A.QM_ENTEROBACTERIA05,    
QM_ENTEROBACTERIA06=A.QM_ENTEROBACTERIA06,    
QM_ENTEROBACTERIA07=A.QM_ENTEROBACTERIA07    
--QM_NUM_NOTIF_1=ISNULL(A.QM_NUM_NOTIF_1,'0')      
FROM #TRAZABILIDAD A         
INNER JOIN TRAZABILIDAD_ETAPA1 B ON A.LOTE_PT=B.LOTE_PT AND A.LOTE_M=B.LOTE_M       
AND A.NRO_LOTE=B.LOTE_DESCARGA        
AND A.NUMINF=B.NUMERO_INFORME AND A.FECHA_PRODUCCION=B.FECHA_PRODUCCION        
            
--INSERTANDO DATOS A TABLA TRAZABILIDAD        
        
INSERT TRAZABILIDAD_ETAPA1        
(COD_PLANTA, PLANTA, FECHA_PRODUCCION, LOTE_PT, MATERIAL_PT, LOTE_M, MATERIAL_MP, UNIDAD_MEDIDA, CANTIDAD_SACOS,         
LOTE_DESCARGA, OBJEK_H, NUMERO_INFORME, CODIGO_EMBARCACION, EMBARCACION, CONSERVACION, FECHA, TIPO_INFORME,         
FECHA_INICIO_DESCARGA, FECHA_FIN_DESCARGA, TEMPERATURA, SISTEMA_FRIO, COD_ZONA_PESCA, NOMBRE_ZONA_PESCA, DESTINO,         
CHATA, CODIGO_TOLVA, FLUJO_TON_HOR, COD_ESPECIE_ACOMP, DESC_ESPECIE_ACOMP, ESPECIE_ACOMP_PORC, COMPMPHUMEDAD,         
COMPMPGRASA, COMPMPSOLIDO, TDC, TVBN, FECHA_INICIO_DES, FECHA_FIN_DES, TM_DECLARADO, POZA1, POZA2, POZA3, POZA4,         
POZA5, POZA6, POZA7, POZA8, POZA9, POZA10, LONGITUD_MINIMA, LONGITUD_MAXIMA, LONGITUD_PROMEDIO, PESO_PROMEDIO,         
MODA_CM, PORCENTAJE_JUVENILES, TOTAL_POZA,LATGRA,LATMIN,LONGRA,LONMIN,QM_HOR_INI_PRO,QM_HOR_FIN_PRO,      
QM_CAL_POT_MP,      
DESCARGA_M,FECHA_M,TM_DESCARGA_M,QM_HOR_INI_RUM,QM_HOR_FIN_RUM,SD_CLASI_COMERCIAL,PROTEINA_DUMAS,      
GRASA,HUMEDAD,CENIZA,ANTIOXIDANTE,SAL,ARENA,TBVN,HISTAMINA,FFA,      
PROTEINA_S3,HUMEDAD_S3,GRANULOMETRIA,DENSIDAD_COMP,TBVN_S3,GRASA_S3,DENSIDAD_APARENTE,NUMERO_FLUJO,CONSUMO_M,      
QM_NUM_NOTIF_1,FECHA_CONSUMO_M,NUM_RUMA,    
QM_SHIGUELLA,QM_SALMONELLA,QM_SALMONELLA02,QM_SALMONELLA03,QM_SALMONELLA04,QM_SALMONELLA05,    
QM_SALMONELLA06,QM_SALMONELLA07,QM_ENTEROBACTERIA,QM_ENTEROBACTERIA02,QM_ENTEROBACTERIA03,    
QM_ENTEROBACTERIA04,QM_ENTEROBACTERIA05,QM_ENTEROBACTERIA06,QM_ENTEROBACTERIA07)        
SELECT         
COD_PLANTA,PLANTA,FECHA_PRODUCCION,LOTE_PT,        
MATERIAL_PT,LOTE_M,MATERIAL_MP,        
MEINS_I AS UNIDAD_MEDIDA,CANTIDAD_SACOS,        
NRO_LOTE AS LOTE_DESCARGA,        
OBJEK_H,NUMINF AS NUMERO_INFORME,CODIGO_EMBARCACION,EMBARCACION,CONSERVACION,FECHA,TIPO_INFORME,        
FECHA_INICIO_DESCARGA,FECHA_FIN_DESCARGA,TEMPERATURA,SISTEMA_FRIO,COD_ZONA_PESCA,        
NOMBRE_ZONA_PESCA,DESTINO,CHATA,CODIGO_TOLVA,flujo_ton_hor,especie_acomp AS COD_ESPECIE_ACOMP,        
descespecieacomp AS DESC_ESPECIE_ACOMP,especie_acomp_porc AS ESPECIE_ACOMP_PORC,        
compmphumedad AS COMPMPHUMEDAD,compmpgrasa AS COMPMPGRASA,        
compmpsolido AS COMPMPSOLIDO,        
TDC,TVBN,FECHA_INICIO_DES,FECHA_FIN_DES,        
TM_DECLARADO,poza1,poza2,poza3,poza4,poza5,poza6,poza7,poza8,poza9,poza10,LONGITUD_MINIMA,        
LONGITUD_MAXIMA,LONGITUD_PROMEDIO,PESO_PROMEDIO,MODA_CM,PORCENTAJE_JUVENILES,TOTAL_POZA,        
LATGRA,LATMIN,LONGRA,LONMIN,QM_HOR_INI_PRO,      
QM_HOR_FIN_PRO,QM_CAL_POT_MP,DESCARGA_M,FECHA_M,TM_DESCARGA_M,QM_HOR_INI_RUM,QM_HOR_FIN_RUM,      
SD_CLASI_COMERCIAL,PROTEINA_DUMAS,      
GRASA,HUMEDAD,CENIZA,ANTIOXIDANTE,SAL,ARENA,TBVN,HISTAMINA,FFA,      
PROTEINA_S3,HUMEDAD_S3,GRANULOMETRIA,DENSIDAD_COMP,TBVN_S3,GRASA_S3,DENSIDAD_APARENTE,NUMERO_FLUJO,CONSUMO_M,      
ISNULL(QM_NUM_NOTIF_1,'0'),FECHA_CONSUMO_M,NULL,    
QM_SHIGUELLA,QM_SALMONELLA,QM_SALMONELLA02,QM_SALMONELLA03,QM_SALMONELLA04,QM_SALMONELLA05,    
QM_SALMONELLA06,QM_SALMONELLA07,QM_ENTEROBACTERIA,QM_ENTEROBACTERIA02,QM_ENTEROBACTERIA03,    
QM_ENTEROBACTERIA04,QM_ENTEROBACTERIA05,QM_ENTEROBACTERIA06,QM_ENTEROBACTERIA07       
FROM #TRAZABILIDAD A        
WHERE NOT EXISTS(SELECT 1 FROM TRAZABILIDAD_ETAPA1 B WHERE        
A.LOTE_PT=B.LOTE_PT AND A.LOTE_M=B.LOTE_M AND A.NRO_LOTE=B.LOTE_DESCARGA        
AND A.NUMINF=B.NUMERO_INFORME AND A.FECHA_PRODUCCION=B.FECHA_PRODUCCION)         
            
----VERIFICAR CASO--      
      
UPDATE A      
SET CANTIDAD_SACOS='1000'      
FROM TRAZABILIDAD_ETAPA1 A      
WHERE LOTE_PT='H105130216'        
      
--------------------------------ACTUALIZANDO DOCUMENTO MATERIAL HORAS RUMAS---------------------      
--ACTUALIZANDO NOTIFICACION EN RUMA      
      
SELECT DISTINCT       
COD_PLANTA,PLANTA,FECHA_PRODUCCION,LOTE_PT,MATERIAL_PT,CANTIDAD_SACOS       
INTO #RUMAS_AGRUPADAS      
FROM TRAZABILIDAD_ETAPA1      
      
SELECT ROW_NUMBER() OVER(PARTITION BY LOTE_PT ORDER BY FECHA_PRODUCCION DESC)AS ORDEN,         
*       
INTO #RUMA      
FROM #RUMAS_AGRUPADAS      
      
SELECT       
C.COD_MATERIAL_LOTE,C.QM_FECPRO,      
CASE WHEN C.QM_HOR_INI_RUM IS NULL THEN '' ELSE QM_HOR_INI_RUM END AS QM_HOR_INI_RUM,      
CASE WHEN C.QM_HOR_FIN_RUM IS NULL THEN '' ELSE QM_HOR_FIN_RUM END AS QM_HOR_FIN_RUM,      
CASE WHEN C.QM_NUM_NOTIF_1 IS NULL THEN '0' ELSE QM_NUM_NOTIF_1 END AS QM_NUM_NOTIF_1,      
CASE WHEN C.QM_LIN_HOR_INI_2 IS NULL THEN '' ELSE QM_LIN_HOR_INI_2 END AS QM_LIN_HOR_INI_2,      
CASE WHEN C.QM_LIN_HOR_FIN_2 IS NULL  THEN '' ELSE QM_LIN_HOR_FIN_2 END AS QM_LIN_HOR_FIN_2,      
CASE WHEN C.QM_NUM_NOTIF_2 IS NULL THEN '' ELSE QM_NUM_NOTIF_2 END AS QM_NUM_NOTIF_2,      
CASE WHEN C.QM_LIN_HOR_INI_3 IS NULL THEN '' ELSE QM_LIN_HOR_INI_3 END AS QM_LIN_HOR_INI_3,      
CASE WHEN C.QM_LIN_HOR_FIN_3 IS NULL THEN '' ELSE QM_LIN_HOR_FIN_3 END AS QM_LIN_HOR_FIN_3,      
CASE WHEN C.QM_NUM_NOTIF_3 IS NULL  THEN '' ELSE QM_NUM_NOTIF_3 END AS QM_NUM_NOTIF_3,      
CASE WHEN C.QM_LIN_HOR_INI_4 IS NULL  THEN '' ELSE QM_LIN_HOR_INI_4 END AS QM_LIN_HOR_INI_4,      
CASE WHEN C.QM_LIN_HOR_FIN_4 IS NULL THEN '' ELSE QM_LIN_HOR_FIN_4 END AS QM_LIN_HOR_FIN_4,      
CASE WHEN C.QM_NUM_NOTIF_4 IS NULL THEN '' ELSE QM_NUM_NOTIF_4 END AS QM_NUM_NOTIF_4      
INTO #LOTES1      
FROM CARACTERISTICAS_SECCION3 C      
--WHERE  SUBSTRING(RTRIM(LTRIM(QM_FECPRO)),1,4)>='2013'      
    
--QM_FECPRO IS NOT NULL AND      
/*      
SELECT * FROM CARACTERISTICAS_SECCION3 B      
WHERE RIGHT(RTRIM(ltrim(B.COD_MATERIAL_LOTE)),10)='H102130417'      
*/      
      
CREATE TABLE #PIVOT(      
COD_MATERIAL_LOTE VARCHAR(30)COLLATE SQL_Latin1_General_CP850_BIN2 NULL,      
FECPRO VARCHAR(8)COLLATE SQL_Latin1_General_CP850_BIN2 NULL,      
QM_HOR_INI_RUM VARCHAR(6) COLLATE SQL_Latin1_General_CP850_BIN2 NULL,      
QM_HOR_FIN_RUM VARCHAR(6)COLLATE SQL_Latin1_General_CP850_BIN2 NULL,      
DOC_MATERIAL VARCHAR(12)COLLATE SQL_Latin1_General_CP850_BIN2 NULL,      
CONCEPTO INT NULL)      
    
--000000000010000004H104130008 error documento con 11 digitos    
      
INSERT INTO #PIVOT      
SELECT COD_MATERIAL_LOTE,QM_FECPRO,QM_HOR_INI_RUM,QM_HOR_FIN_RUM,QM_NUM_NOTIF_1,1 AS CONCEPTO      
FROM #LOTES1      
UNION      
SELECT COD_MATERIAL_LOTE,QM_FECPRO,QM_LIN_HOR_INI_2,QM_LIN_HOR_FIN_2,QM_NUM_NOTIF_2,2 AS CONCEPTO       
FROM #LOTES1      
UNION      
SELECT COD_MATERIAL_LOTE,QM_FECPRO,QM_LIN_HOR_INI_3,QM_LIN_HOR_FIN_3,QM_NUM_NOTIF_3,3 AS CONCEPTO      
FROM #LOTES1      
UNION      
SELECT COD_MATERIAL_LOTE,QM_FECPRO,QM_LIN_HOR_INI_4,QM_LIN_HOR_FIN_4,QM_NUM_NOTIF_4,4 AS CONCEPTO      
FROM #LOTES1      
    
--CASO SOLO EXISTA UNA NOTIFICACION    
    
  SELECT *    
  INTO #CEROS     
  FROM #PIVOT    
  WHERE DOC_MATERIAL='0'    
      
SELECT CONVERT(DATETIME,B.FECPRO)AS FECHA_PRODUCCION,      
CONVERT(DATETIME,A.BUDAT)AS FECHA_PROD_DOC,      
A.WERKS_I AS COD_PLANTA,      
RIGHT(RTRIM(ltrim(B.COD_MATERIAL_LOTE)),10)AS LOTE_PT,      
B.QM_HOR_INI_RUM,B.QM_HOR_FIN_RUM,B.CONCEPTO,      
A.CHARG_I AS LOTE_M,A.MBLNR      
INTO #INFO      
FROM DOCUMENTO_MATERIAL A      
INNER JOIN #PIVOT B ON A.MBLNR=B.DOC_MATERIAL       
WHERE MATNR_I='000000000016000000'     
and B.DOC_MATERIAL<>'0'     
--AND RIGHT(RTRIM(ltrim(B.COD_MATERIAL_LOTE)),10)='H102130417'      
    
      
--ACTUALIZANDO CONCEPTO      
--CASO CEROS    
  UPDATE A    
  SET NUM_RUMA=B.CONCEPTO,    
   QM_NUM_NOTIF_1=B.DOC_MATERIAL    
FROM TRAZABILIDAD_ETAPA1 A     
INNER JOIN #CEROS B ON A.LOTE_PT=RIGHT(RTRIM(ltrim(B.COD_MATERIAL_LOTE)),10)      
--AND A.FECHA_PRODUCCION=CONVERT(DATETIME,SUBSTRING(FECPRO,1,4)+'-'+SUBSTRING(FECPRO,5,2)+'-'+SUBSTRING(FECPRO,7,2))    
--WHERE A.LOTE_PT='H102130417'    
    
UPDATE A      
SET      
NUM_RUMA=B.CONCEPTO,      
QM_NUM_NOTIF_1=B.MBLNR       
FROM TRAZABILIDAD_ETAPA1 A      
INNER JOIN #INFO B ON A.COD_PLANTA=B.COD_PLANTA AND A.FECHA_PRODUCCION=B.FECHA_PROD_DOC      
AND RTRIM(LTRIM(A.LOTE_PT))=RTRIM(LTRIM(B.LOTE_PT)) AND RTRIM(LTRIM(A.LOTE_M))=RTRIM(LTRIM(B.LOTE_M))      
      
      
--ACTUALIZANDO RUMA      
      
UPDATE A      
SET       
QM_HOR_INI_RUM=CASE WHEN A.NUM_RUMA=1 THEN     
SUBSTRING(B.QM_HOR_INI_RUM,1,2)+':'+SUBSTRING(B.QM_HOR_INI_RUM,3,2)+':'+SUBSTRING(B.QM_HOR_INI_RUM,5,2)    
   ELSE     
   CASE WHEN A.NUM_RUMA=2 THEN     
 SUBSTRING(B.QM_LIN_HOR_INI_2,1,2)+':'+SUBSTRING(B.QM_LIN_HOR_INI_2,3,2)+':'+SUBSTRING(B.QM_LIN_HOR_INI_2,5,2)    
 ELSE     
 CASE WHEN NUM_RUMA=3 THEN     
  SUBSTRING(B.QM_LIN_HOR_INI_3,1,2)+':'+SUBSTRING(B.QM_LIN_HOR_INI_3,3,2)+':'+SUBSTRING(B.QM_LIN_HOR_INI_3,5,2)    
  ELSE     
  CASE WHEN NUM_RUMA=4 THEN     
  SUBSTRING(B.QM_LIN_HOR_INI_4,1,2)+':'+SUBSTRING(B.QM_LIN_HOR_INI_4,3,2)+':'+SUBSTRING(B.QM_LIN_HOR_INI_4,5,2)    
  ELSE ''    
  END    
   END     
    END     
     END,    
QM_HOR_FIN_RUM=    
CASE WHEN A.NUM_RUMA=1 THEN     
SUBSTRING(B.QM_HOR_FIN_RUM,1,2)+':'+SUBSTRING(B.QM_HOR_FIN_RUM,3,2)+':'+SUBSTRING(B.QM_HOR_FIN_RUM,5,2)    
   ELSE     
   CASE WHEN A.NUM_RUMA=2 THEN     
 SUBSTRING(B.QM_LIN_HOR_FIN_2,1,2)+':'+SUBSTRING(B.QM_LIN_HOR_FIN_2,3,2)+':'+SUBSTRING(B.QM_LIN_HOR_FIN_2,5,2)    
 ELSE     
  CASE WHEN A.NUM_RUMA=3 THEN    
 SUBSTRING(B.QM_LIN_HOR_FIN_3,1,2)+':'+SUBSTRING(B.QM_LIN_HOR_FIN_3,3,2)+':'+SUBSTRING(B.QM_LIN_HOR_FIN_3,5,2)    
  ELSE     
  CASE WHEN A.NUM_RUMA=4 THEN    
  SUBSTRING(B.QM_LIN_HOR_FIN_4,1,2)+':'+SUBSTRING(B.QM_LIN_HOR_FIN_4,3,2)+':'+SUBSTRING(B.QM_LIN_HOR_FIN_4,5,2)    
  ELSE '' END     
  END     
    END     
      END     
FROM TRAZABILIDAD_ETAPA1 A      
INNER JOIN CARACTERISTICAS_SECCION3 B ON B.COD_MATERIAL_LOTE=RTRIM(LTRIM(A.MATERIAL_PT))+RTRIM(LTRIM(A.LOTE_PT))      
     
     
 /*ACTUALIZANDO DATOS DE MATERIAL*/    
     
UPDATE A    
SET COMPMPHUMEDAD='74.550000',    
    COMPMPGRASA='4.620000',    
    COMPMPSOLIDO='20.830000'    
FROM TRAZABILIDAD_ETAPA1 A    
WHERE FECHA_PRODUCCION='2013-11-21'and COD_PLANTA='H105'    
AND LOTE_PT='H105130433'AND LOTE_M='M050600715'    
  
UPDATE B  
SET CANTIDAD_SACOS='200'  
FROM TRAZABILIDAD_ETAPA1 B   
WHERE LOTE_PT='H105150285'AND LOTE_M='M050401639'AND   
FECHA_PRODUCCION='2015-05-22 00:00:00.000'  
AND COD_PLANTA='H105'  
      
DROP TABLE #LOTES1      
DROP TABLE #PIVOT      
DROP TABLE #INFO      
DROP TABLE #RUMA      
DROP TABLE #RUMAS_AGRUPADAS      
       
DROP TABLE #HARINA        
DROP TABLE #PT        
DROP TABLE #ANULADOS        
DROP TABLE #SIN_ANULADOS        
DROP TABLE #RUMA_LOTEM        
DROP TABLE #LOTE_PT_M_H        
DROP TABLE #INFORMES_FLOTA        
DROP TABLE #CALAS        
DROP TABLE #ORDEN_CALAS        
DROP TABLE #INFORME_CALIDAD        
DROP TABLE #TRAZABILIDAD    
DROP TABLE #CEROS        
        
        
END
