ALTER VIEW [dbo].[VF_DISTRIBUCION]
AS
SELECT
A.ID_MANDANTE,A.ID_MEDIDA,A.ID_UNIDAD_NEGOCIO,
A.ID_CENTRO,A.ID_ALMACEN,A.ID_MATERIAL,
A.ID_TIEMPO,A.ID_TIEMPO_CONT,A.ID_LOTE,
CASE WHEN A.VAL_RESIDUOS=0 THEN NULL ELSE A.VAL_RESIDUOS END AS VAL_RESIDUOS,
CASE WHEN A.VAL_DESCARTE=0 THEN NULL ELSE A.VAL_DESCARTE END AS VAL_DESCARTE,
CASE WHEN A.VAL_CONSUMO_MP=0 THEN NULL ELSE A.VAL_CONSUMO_MP END AS VAL_CONSUMO_MP,
CASE WHEN A.VAL_CONSUMO_ALM=0 THEN NULL ELSE A.VAL_CONSUMO_ALM END AS VAL_CONSUMO_ALM,
A.ID_DOC_MATERIAL,
A.ID_ORD_FABRIC,A.ID_MATERIAL_P,
CASE WHEN A.VAL_PRODUCCION=0 THEN NULL ELSE A.VAL_PRODUCCION END AS VAL_PRODUCCION,
VAL_CAL_A_B = (CASE WHEN B.CALIDAD_LOTE in ('CALIDAD A','CALIDAD B') THEN A.VAL_PRODUCCION ELSE 0.0000 END),
VAL_CAL_A_B_C = (CASE WHEN B.CALIDAD_LOTE in ('CALIDAD A','CALIDAD B','CALIDAD C') THEN A.VAL_PRODUCCION ELSE 0.0000 END)
from F_DISTRIBUCION A
left outer join D_LOTES B on A.ID_MANDANTE = B.ID_MANDANTE and A.ID_LOTE = B.ID_LOTE
