CREATE VIEW [dbo].[VF_DISTRIBUCION]
AS
SELECT 
ID_MANDANTE,ID_MEDIDA,ID_UNIDAD_NEGOCIO,
ID_CENTRO,ID_ALMACEN,ID_MATERIAL,
ID_TIEMPO,ID_TIEMPO_CONT,ID_LOTE,
CASE WHEN VAL_RESIDUOS=0 THEN NULL ELSE VAL_RESIDUOS END AS VAL_RESIDUOS,
CASE WHEN VAL_DESCARTE=0 THEN NULL ELSE VAL_DESCARTE END AS VAL_DESCARTE,
CASE WHEN VAL_CONSUMO_MP=0 THEN NULL ELSE VAL_CONSUMO_MP END AS VAL_CONSUMO_MP,
CASE WHEN VAL_CONSUMO_ALM=0 THEN NULL ELSE VAL_CONSUMO_ALM END AS VAL_CONSUMO_ALM,
ID_DOC_MATERIAL,
ID_ORD_FABRIC,ID_MATERIAL_P,
CASE WHEN VAL_PRODUCCION=0 THEN NULL ELSE VAL_PRODUCCION END AS VAL_PRODUCCION
from F_DISTRIBUCION
