
-- TRUNCATE TABLE CARGA_STAGE_LOG -- DROP TABLE CARGA_STAGE_LOG
-- EXEC [dbo].[USP_STG_CARGA_MODULO] 'PM', 'M';
SELECT * FROM CARGA_STAGE_LOG
WHERE HORARIO = 'TEST'

-- DURACION
WITH x AS (SELECT FECHA, MODULO_SAP, TABLA_STAGE, MENSAJE,
  d = DATEDIFF(SECOND, FECHA_INI, FECHA_FIN)
  FROM CARGA_STAGE_LOG
)
SELECT FECHA, MODULO_SAP, TABLA_STAGE, MENSAJE,
  [HH:MM:SS] = CASE WHEN d >= 3600 THEN 
    CONVERT(VARCHAR(5), d/60/60) + ':' ELSE '' END
  + RIGHT('0' + CONVERT(VARCHAR(2), d/60%60), 2)
  + ':' + RIGHT('0' + CONVERT(VARCHAR(2), d % 60), 2)
FROM x
WHERE 1 = 1
AND FECHA = '2016-09-26'
AND TABLA_STAGE = 'MAESTROS_CTAS_MAYOR'
ORDER BY 5 DESC;

-- Duracion total
WITH x AS (SELECT FECHA, MODULO_SAP, HORARIO,
  d = DATEDIFF(SECOND, MIN(FECHA_INI), MAX(FECHA_FIN))
  FROM CARGA_STAGE_LOG
  GROUP BY FECHA, MODULO_SAP, HORARIO
)
SELECT FECHA, MODULO_SAP, HORARIO,
  [HH:MM:SS] = CASE WHEN d >= 3600 THEN 
    CONVERT(VARCHAR(5), d/60/60) + ':' ELSE '' END
  + RIGHT('0' + CONVERT(VARCHAR(2), d/60%60), 2)
  + ':' + RIGHT('0' + CONVERT(VARCHAR(2), d % 60), 2)
FROM x
WHERE 1 = 1
--AND FECHA = '2016-09-22'
AND MODULO_SAP = 'PM'
order by 1
;




