CREATE TABLE CARGA_STAGE_LOG (
	LOG_ID INT IDENTITY(1,1),
	MODULO_SAP VARCHAR(75),
	TABLA_SAP VARCHAR(75),
	TABLA_STAGE VARCHAR(75),
	FECHA DATE,
	HORARIO VARCHAR(75),
	FECHA_INI DATETIME,
	FECHA_FIN DATETIME,
	DURACION INT,
	REGISTROS INT,
	MENSAJE VARCHAR(MAX),
	EXITO INT
);
