-- sp_refreshview VF_PBI_CONSUMO_COMBUSTIBLE
-- select * from VF_PBI_CONSUMO_COMBUSTIBLE

ALTER VIEW [dbo].[VF_PBI_CONSUMO_COMBUSTIBLE] AS
SELECT t9.ID_TIEMPO, ID_TEMP_PESCA = (SELECT TOP 1 TP.ID_TEMP_PESCA FROM VD_TEMPORADA_PESCA TP WHERE t9.FECH_DIA_SAP BETWEEN TP.FEC_INICIO AND TP.FEC_FIN),
t3.ID_CENTRO, SUM(t1.VAL_CONSUMO_ALM) AS CONSUMO_COMBUSTIBLE,
CASE
	WHEN t3.ID_CENTRO = 5 THEN CAST(36.06 AS Decimal(8, 2))
	WHEN t3.ID_CENTRO = 6 THEN CAST(37.00 AS Decimal(8, 2))
	WHEN t3.ID_CENTRO = 9 THEN CAST(37.00 AS Decimal(8, 2))
END AS META_PLANTA
FROM VF_CONSUMOS t1 (NOLOCK)
INNER JOIN VD_CENTRO_MM t3 (NOLOCK) ON t1.ID_CENTRO = t3.ID_CENTRO
INNER JOIN VD_MATERIAL t4 (NOLOCK) ON t1.ID_MATERIAL = t4.ID_MATERIAL
INNER JOIN VD_TIEMPO (NOLOCK) t9 ON t1.ID_TIEMPO = t9.ID_TIEMPO
INNER JOIN VD_ORDENES_FABRICACION (NOLOCK) t5 ON t1.ID_ORD_FABRIC = t5.ID_ORD_REPR
WHERE t4.DES_MATERIAL IN ('GAS LICUADO DE PETROLEO','PETROLEO BUNKER N° 6','PETROLEO INDUSTRIAL R-500')
AND t4.DES_RAMO = 'PESCA'
AND t3.ID_CENTRO in (9,6,5) -- VEGUETA, MALABRIGO, COISHCO
AND t5.KTEXT in ('Harina de Anchoveta Turno A','Harina de Anchoveta Turno B')
--AND t9.DESC_FECH_2 = '21/06/2016'
GROUP BY t9.ID_TIEMPO, t3.ID_CENTRO, FECH_DIA_SAP

UNION ALL

SELECT t9.ID_TIEMPO, ID_TEMP_PESCA = (SELECT TOP 1 TP.ID_TEMP_PESCA FROM VD_TEMPORADA_PESCA TP WHERE t9.FECH_DIA_SAP BETWEEN TP.FEC_INICIO AND TP.FEC_FIN),
t3.ID_CENTRO, SUM(t1.GAS) AS CONSUMO_COMBUSTIBLE,
CAST(43.50 AS Decimal(8, 2)) AS META_PLANTA
FROM VF_NOTIFICACION_ORDEN (NOLOCK) t1
INNER JOIN VD_CENTRO_MM t3 (NOLOCK) ON t1.ID_CENTRO = t3.ID_CENTRO
INNER JOIN VD_TIEMPO (NOLOCK) t9 ON t1.ID_TIEMPO = t9.ID_TIEMPO
WHERE t3.ID_CENTRO in (10) -- TAMBO DE MORA
-- AND t9.DESC_FECH_2 = '05/07/2016'
GROUP BY t9.ID_TIEMPO, t3.ID_CENTRO, FECH_DIA_SAP









-- TEST

select ID_CENTRO, DES_CENTRO
from VD_CENTRO_MM (NOLOCK)
where ID_CENTRO in (9,6,5)

	CASE
		WHEN t3.ID_CENTRO = 5 THEN CAST(36.06 AS Decimal(8, 2))
		WHEN t3.ID_CENTRO = 6 THEN CAST(37.00 AS Decimal(8, 2))
		WHEN t3.ID_CENTRO = 9 THEN CAST(37.00 AS Decimal(8, 2))
	END AS META_PLANTA

/*
6 Malabrigo 37.00 
5 Coishco 36.06
9 Vegueta 37.00
Tambo de Mora 43.50 
*/


select * from VD_MATERIAL
where DES_MATERIAL = 'GAS LICUADO DE PETROLEO'

select TOP 1000 * from VF_CONSUMOS
select * from VD_ORDENES_FABRICACION

select * from [VF_PBI_CONSUMO_COMBUSTIBLE]

select top 1000 * from VF_PRODUCCION
VF_PRODUCCION.VAL_PRODUCCION (Double)



select top 1000 * from VF_CONSUMOS
select top 1000 * from VF_NOTIFICACION_ORDEN

