-- sp_refreshview [VF_PBI_CALIDAD_REAL_TBVN]
-- sp_refreshview [VD_PBI_CALIDAD_REAL_TBVN]

ALTER VIEW [dbo].[VF_PBI_CALIDAD_REAL_TBVN] AS
WITH TBVN AS (
	SELECT S.ID_TIEMPO, ID_TEMP_PESCA = (SELECT TOP 1 TP.ID_TEMP_PESCA FROM VD_TEMPORADA_PESCA TP WHERE S.FECH_DIA_SAP BETWEEN TP.FEC_INICIO AND TP.FEC_FIN),
	CC.ID_CENTRO, 1 AS ID_TIPO_INFORME, -- A.FECDES2, D.NAME2
	CASE WHEN CAST(X.QM_TBVN AS NUMERIC(20,2))<=30 THEN SUM(C.LOTE_MP) ELSE 0 END AS SP_P,
	SUM(C.LOTE_MP) AS MP_RECIBIDA
	FROM STAGE_SAP_PRD.dbo.INFORME_FLOTA A (NOLOCK)
	INNER JOIN STAGE_SAP_PRD.dbo.ORDEN_FABRICACION_DET B (NOLOCK) ON A.MANDT = B.MANDT and A.AUFNR = B.AUFNR and A.MATNR = B.MATNR  
	INNER JOIN STAGE_SAP_PRD.dbo.PROCESO_DETALLE C (NOLOCK) ON A.MANDT=A.MANDT AND B.CHARG=C.NRO_LOTE
	INNER JOIN STAGE_SAP_PRD.dbo.PROCESO_CABECERA C1 (NOLOCK) on C.MANDT = C1.MANDT and C.COD_PRO = C1.COD_PRO
	INNER JOIN STAGE_SAP_PRD.dbo.CENTRO (NOLOCK) D ON A.WERDES = D.WERKS
	INNER JOIN STAGE_SAP_PRD.dbo.SECCION_1 X (NOLOCK) ON ('000000000016000000' + C1.LOTE) = X.MATERIAL_LOTE
	INNER JOIN D_TIEMPO S (NOLOCK) ON A.FECDES2 =S.FECH_DIA_SAP
	LEFT OUTER JOIN D_CENTRO_MM CC (NOLOCK) ON CC.DES_CENTRO2 = D.NAME2
	WHERE   
	A.MANDT = 300  AND A.PESCA = 'X' 
	AND DESTIN = 'CHI'  AND A.TIPINF = 'P'
	AND A.AUFNR <> ''
	AND D.NAME2 in ('COISHCO','MALABRIGO','VEGUETA','TAMBO DE MORA') -- ('COISHCO') 
	--AND A.FECDES2 BETWEEN '20160618' AND '20160713'
	AND C.[STATUS] = 'S'
	GROUP BY S.ID_TIEMPO, CC.ID_CENTRO, QM_TBVN, FECH_DIA_SAP

	UNION ALL

	SELECT S.ID_TIEMPO, ID_TEMP_PESCA = (SELECT TOP 1 TP.ID_TEMP_PESCA FROM VD_TEMPORADA_PESCA TP WHERE S.FECH_DIA_SAP BETWEEN TP.FEC_INICIO AND TP.FEC_FIN),
	CC.ID_CENTRO, 2 AS ID_TIPO_INFORME, -- A.FECDES2, D.NAME2
	CASE WHEN CAST(X.QM_TBVN AS NUMERIC(20,2))<=30 THEN SUM(C.LOTE_MP) ELSE 0 END AS SP_P,
	SUM(C.LOTE_MP) AS MP_RECIBIDA
	FROM STAGE_SAP_PRD.dbo.INFORME_FLOTA A (NOLOCK)
	INNER JOIN STAGE_SAP_PRD.dbo.REPARTO_PLAN_ENTREGA B (NOLOCK) on A.MANDT = B.MANDT and A.EBELN = B.EBELN  
	INNER JOIN STAGE_SAP_PRD.dbo.PROCESO_DETALLE C (NOLOCK) ON A.MANDT=A.MANDT AND B.CHARG=C.NRO_LOTE
	INNER JOIN STAGE_SAP_PRD.dbo.PROCESO_CABECERA (NOLOCK) C1 on C.MANDT = C1.MANDT and C.COD_PRO = C1.COD_PRO
	INNER JOIN STAGE_SAP_PRD.dbo.CENTRO (NOLOCK) D ON A.WERDES = D.WERKS
	INNER JOIN STAGE_SAP_PRD.dbo.SECCION_1 (NOLOCK) X ON ('000000000016000000' + C1.LOTE) = X.MATERIAL_LOTE
	INNER JOIN D_TIEMPO (NOLOCK) S on A.FECDES2 =S.FECH_DIA_SAP
	LEFT OUTER JOIN D_CENTRO_MM (NOLOCK) CC on CC.DES_CENTRO2 = D.NAME2
	WHERE   
	A.MANDT = 300  AND A.PESCA = 'X' 
	AND DESTIN = 'CHI'  AND A.TIPINF = 'T'
	AND A.EBELN <> ''
	AND D.NAME2 in ('COISHCO','MALABRIGO','VEGUETA','TAMBO DE MORA') -- ('COISHCO') 
	-- AND A.FECDES2 BETWEEN '20160618' AND '20160713'
	AND C.[STATUS] = 'S'
	GROUP BY S.ID_TIEMPO, CC.ID_CENTRO, QM_TBVN, FECH_DIA_SAP
) SELECT ID_TIEMPO, ID_TEMP_PESCA, ID_CENTRO, ID_TIPO_INFORME,
SUM(SP_P) AS SP_P, SUM(MP_RECIBIDA) AS MP_RECIBIDA
FROM TBVN
GROUP BY ID_TIEMPO, ID_TEMP_PESCA, ID_CENTRO, ID_TIPO_INFORME
--Select * from VF_PBI_CALIDAD_REAL_TBVN

ALTER VIEW [dbo].[VD_PBI_CALIDAD_REAL_TBVN] AS -- select * from [VD_PBI_CALIDAD_REAL_TBVN]
SELECT 1 AS ID_TIPO_INFORME, 'PROPIO' AS TIPO_INFORME
UNION
SELECT 2 , 'TERCEROS'

-- Query Origen:

SELECT   
b.MANDT,    
b.LOTE AS LOTE_M,  
'000000000016000000'AS Material_MP,  
a.NRO_LOTE,  
a.EMBARCA,
b.FECHA AS FECHA_M,  
LOTE_MP AS TM_DESCARGA,
b.TOTAL_TN AS TOTAL_M 
INTO #LOTE_PT_M_H  
from PROCESO_DETALLE a  
inner join PROCESO_CABECERA b on a.MANDT = b.MANDT and a.COD_PRO = b.COD_PRO   
where a.[STATUS] = 'S'   


CREATE TABLE #INFORMES_FLOTA  
(  
MANDT VARCHAR(6)COLLATE SQL_Latin1_General_CP850_BIN2 NULL,
LOTE_M varchar(18)COLLATE SQL_Latin1_General_CP850_BIN2 NULL,
MATERIAL_MP varchar(18)COLLATE SQL_Latin1_General_CP850_BIN2 NULL,      
LOTE_H varchar(10)COLLATE SQL_Latin1_General_CP850_BIN2 NULL,  
EMBARCA varchar(40)COLLATE SQL_Latin1_General_CP850_BIN2 NULL,  
TM_DESCARGA numeric(20,4)NULL,  
NUMINF varchar(6) COLLATE SQL_Latin1_General_CP850_BIN2 NULL,  
TIPINF varchar(1) COLLATE SQL_Latin1_General_CP850_BIN2 NULL,  
[STATUS] varchar(3) COLLATE SQL_Latin1_General_CP850_BIN2 NULL,  
OBJEK_H varchar(60)COLLATE SQL_Latin1_General_CP850_BIN2 NULL,  
TIPO_H CHAR(1)COLLATE SQL_Latin1_General_CP850_BIN2 NULL,
FECHA_M VARCHAR(8)NULL,
TOTAL_M numeric(20,4)null,
MATNR varchar(36) COLLATE SQL_Latin1_General_CP850_BIN2 null,
CHARG varchar(20) COLLATE SQL_Latin1_General_CP850_BIN2 null
)  
CREATE INDEX #I_OPT ON #INFORMES_FLOTA (MANDT, MATNR, CHARG)

---PROPIO  
INSERT INTO #INFORMES_FLOTA   
SELECT   
C.MANDT,C.LOTE_M,C.Material_MP,
C.NRO_LOTE,
C.EMBARCA,C.TM_DESCARGA,  
A.NUMINF, A.TIPINF, A.[STATUS],   
(rtrim(ltrim(A.MATNR)) + rtrim(ltrim(B.CHARG))) as OBJEK_H, 'H',
C.FECHA_M,TOTAL_M,A.MATNR, 
B.CHARG
FROM INFORME_FLOTA A (nolock)  
inner join ORDEN_FABRICACION_DET B (nolock) on A.MANDT = B.MANDT and A.AUFNR = B.AUFNR and A.MATNR = B.MATNR  
INNER JOIN #LOTE_PT_M_H C (nolock)on A.MANDT=A.MANDT AND B.CHARG=C.NRO_LOTE  
where   
A.MANDT = @ParamMandante  
and A.PESCA = 'X' 
and DESTIN = 'CHI'  
and A.TIPINF = 'P'
and A.AUFNR <> '' 
and A.WERDES = @ParamCentro
and (CASE WHEN left(rtrim(ltrim(A.HORDES2)),4) between '0001' and '0700' 
                  then convert(varchar(8), convert(datetime,A.FECDES2) - 1, 112) else A.FECDES2 end) 
                  between convert(varchar(8),convert(datetime,@ParamFechaInicio),112) 
                  and convert(varchar(8),convert(datetime,@ParamFechaFinal),112)
   
--TERCEROS  
  
INSERT INTO #INFORMES_FLOTA  
SELECT  DISTINCT
C.MANDT,C.LOTE_M,C.Material_MP,
C.NRO_LOTE,  
C.EMBARCA,C.TM_DESCARGA,  
A.NUMINF, A.TIPINF, A.[STATUS],   
(rtrim(ltrim(A.MATNR)) + rtrim(ltrim(B.CHARG))) as OBJEK_H, 'H',
C.FECHA_M,TOTAL_M,A.MATNR, 
B.CHARG
FROM INFORME_FLOTA A (nolock)  
INNER JOIN REPARTO_PLAN_ENTREGA B (nolock) on A.MANDT = B.MANDT and A.EBELN = B.EBELN  
INNER JOIN #LOTE_PT_M_H C (nolock)on A.MANDT=A.MANDT AND B.CHARG=C.NRO_LOTE  
where A.MANDT = @ParamMandante
and A.PESCA = 'X' and DESTIN = 'CHI'  
and A.TIPINF = 'T'and A.EBELN <> ''
and A.WERDES = @ParamCentro
and (CASE WHEN left(rtrim(ltrim(A.HORDES2)),4) between '0001' and '0700' 
                  then convert(varchar(8), convert(datetime,A.FECDES2) - 1, 112) else A.FECDES2 end) 
                  between convert(varchar(8),convert(datetime,@ParamFechaInicio),112) 
                  and convert(varchar(8),convert(datetime,@ParamFechaFinal),112)
                  
SELECT  
H.MANDT, 
H.LOTE_H,H.LOTE_M,  
H.EMBARCA,H.TM_DESCARGA,H.NUMINF,H.TIPINF,H.[STATUS],H.OBJEK_H,H.TIPO_H  
PP_EMBARCACION, PP_HABIL_CHD,PP_RSW, PP_TEMPERATURA, PP_ZONA_PESCA,  
PP_PRESEN_COMBUSTIBLE,PP_MATERIAL_EXTRANO,PP_CHATA,PP_TOLVA,  
PP_POZA1,PP_POZA2,PP_POZA3,PP_POZA4,PP_POZA5,PP_POZA6,PP_POZA7,  
PP_POZA8,PP_POZA9,PP_POZA10,PP_DESCARGA_TM_H,QM_LONG_MIN,QM_LONG_MAX,  
QM_TBVN=(SELECT QM_TBVN FROM SECCION_1 X WHERE (H.MATERIAL_MP+H.LOTE_M)=X.MATERIAL_LOTE),  
CONVERT(DATETIME,PP_FECINI_DESCARGA)AS FECHA_INICIO_DESCARGA,  
CONVERT(DATETIME,PP_FECFIN_DESCARGA)AS FECHA_FINAL_DESCARGA,  
PP_HR_INI_DESCARGA,  
PP_HR_FIN_DESCARGA,  
H.TM_DESCARGA AS DESCARGA_M,
H.FECHA_M,H.TOTAL_M
INTO #INFORME_CALIDAD  
FROM SECCION_1 A  
INNER JOIN #INFORMES_FLOTA H on A.MANDT = H.MANDT and A.MATERIAL_LOTE = (H.MATNR + H.CHARG)


SELECT
A.MATRICULA		as idembarcacion,
CASE WHEN left(rtrim(ltrim(A.HORDES2)),4) between '0001' and '0700' 
                  then convert(varchar(8), 
convert(datetime,A.FECDES2) - 1, 112) else A.FECDES2 end AS Fecha,
A.EMBARC		as embarca_nombre,
A.TIPINF as Tipo_Informe,
CONVERT(DATETIME,CONVERT(CHAR(10),CONVERT (DATETIME,FECDES2),120)+' '+  
SUBSTRING(HORDES2,1,2)+':'+SUBSTRING(HORDES2,3,2)  
+':'+SUBSTRING(HORDES2,5,2))as Fecha_Fin_Descarga,
B.PP_HABIL_CHD	as habilitad_chd,
B.PP_TEMPERATURA	as 	 tolvatemp,
B.PP_RSW		as Sistema_frio,
B.PP_ZONA_PESCA	as  zona_pesca,
B.PP_ZONA_PESCA	as  Nomb_zona_pesca,
A.DESTIN		as Consumo_Chd_ChI,
B.PP_PRESEN_COMBUSTIBLE as Combustible,
B.PP_MATERIAL_EXTRANO	as Materiales_Extraños,
B.PP_CHATA		as chata,
B.PP_TOLVA		as codtolva,
A.NUMINF		as numero_reporte,
B.PP_DESCARGA_TM_H as flujo_ton_hor,
B.QM_TBVN		  as TVBN,
A.FECDES1 as fecha_ini,
A.FECDES2 as fecha_fin,
tm_declarado = (select sum(x1.TBODE) from CALAS x1
			     where x1.MANDT = A.MANDT and x1.NUMINF = A.NUMINF),
--A.GWEMG	  as tot_poza,
B.PP_POZA1 as poza1,
B.PP_POZA2 as poza2,
B.PP_POZA3 as poza3,
B.PP_POZA4 as poza4,
B.PP_POZA5 as poza5,
B.PP_POZA6 as poza6,
B.PP_POZA7 as poza7,
B.PP_POZA8 as poza8,
B.PP_POZA9 as poza9,
B.PP_POZA10 as poza10,
B.QM_LONG_MIN as rango_min,
B.QM_LONG_MAX as rango_max,
tot_poza = (CASE WHEN A.TIPINF = 'P' THEN (SELECT SUM(z.IGMNG)FROM ORDEN_FABRICACION z 
					where z.MANDT=A.MANDT and z.AUFNR=A.AUFNR)
				 WHEN A.TIPINF = 'T' THEN (SELECT SUM(y.MENGE)FROM ORDEN_COMPRA_DET y 
					where y.MANDT=A.MANDT and y.EBELN=A.EBELN)
				 ELSE A.GWEMG END),
B.DESCARGA_M,
B.FECHA_M,B.TOTAL_M
INTO #SECCION_1
from INFORME_FLOTA A (nolock)
INNER JOIN #INFORME_CALIDAD B on A.MANDT = B.MANDT and A.NUMINF = B.NUMINF
where A.MANDT = @ParamMandante
and A.PESCA = 'X' 
and DESTIN = 'CHI'
and A.WERDES = @ParamCentro
and (CASE WHEN left(rtrim(ltrim(A.HORDES2)),4) between '0001' and '0700' 
                  then convert(varchar(8), convert(datetime,A.FECDES2) - 1, 112) else A.FECDES2 end) 
                  between convert(varchar(8),convert(datetime,@ParamFechaInicio),112) 
                  and convert(varchar(8),convert(datetime,@ParamFechaFinal),112)
--AND B.QM_TBVN IS NULL

SELECT 
convert(char(10),convert(datetime,Fecha),103) as FECHA,
Fecha AS FECHA_ORDEN,
Fecha_Fin_Descarga,
idembarcacion as ID_EMBARCACION,
embarca_nombre as LANCHA,
Sistema_frio as RSW,
tolvatemp as TEMPERATURA,
tm_declarado as DECLARADO,
tot_poza as RECIBIDO,
Tipo_Informe as COD_TIPO_INFORME,
CASE WHEN Tipo_Informe='P' THEN 'Propios'
     WHEN Tipo_Informe='T' THEN 'Terceros'end TIPO_INFORME,
TVBN,
CASE WHEN CAST(TVBN AS NUMERIC(20,2))<=20 THEN 'TVBN<=20'
	 WHEN CAST(TVBN AS NUMERIC(20,2))>20 AND CAST(TVBN AS NUMERIC(20,2))<=25 THEN '20<TVBN<=25'
	 WHEN CAST(TVBN AS NUMERIC(20,2))>25 AND CAST(TVBN AS NUMERIC(20,2))<=30 THEN '25<TVBN<=30'
	 WHEN CAST(TVBN AS NUMERIC(20,2))>30 AND CAST(TVBN AS NUMERIC(20,2))<=50 THEN '30<TVBN<=50'
	 WHEN CAST(TVBN AS NUMERIC(20,2))>50 AND CAST(TVBN AS NUMERIC(20,2))<=75 THEN '50<TVBN<=75'
	 WHEN CAST(TVBN AS NUMERIC(20,2))>75 AND CAST(TVBN AS NUMERIC(20,2))<=100 THEN '75<TVBN<=100'
	 WHEN CAST(TVBN AS NUMERIC(20,2))>100 THEN 'TVBN>100'
	 ELSE 'SIN TVBN'END AS AGRUPACION_TVBN, 
	 CASE WHEN CAST(TVBN AS NUMERIC(20,2))<=20 THEN 1
	 WHEN CAST(TVBN AS NUMERIC(20,2))>20 AND CAST(TVBN AS NUMERIC(20,2))<=25 THEN 2
	 WHEN CAST(TVBN AS NUMERIC(20,2))>25 AND CAST(TVBN AS NUMERIC(20,2))<=30 THEN 3
	 WHEN CAST(TVBN AS NUMERIC(20,2))>30 AND CAST(TVBN AS NUMERIC(20,2))<=50 THEN 4 
	 WHEN CAST(TVBN AS NUMERIC(20,2))>50 AND CAST(TVBN AS NUMERIC(20,2))<=75 THEN 5
	 WHEN CAST(TVBN AS NUMERIC(20,2))>75 AND CAST(TVBN AS NUMERIC(20,2))<=100 THEN 6
	 WHEN CAST(TVBN AS NUMERIC(20,2))>100 THEN 7 
	 ELSE 0
	 END AS ORDEN_AGRUPACION_TVBN,
	 TOTAL_M,FECHA_M,DESCARGA_M
into #final
FROM #SECCION_1
order by Fecha

select * from #final

--DROP INDEX #I_OPT ON #INFORMES_FLOTA
DROP TABLE #INFORMES_FLOTA 
DROP TABLE #INFORME_CALIDAD 





